'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('Agent contracts separate registration data, normalized state, patches, and disposable ownership', () => {
  const source = [
    'import {',
    '  AgentPhase,',
    '  AgentSessionStatus,',
    '  AgentStateStore,',
    '  applyAgentStatePatch,',
    '  createAgentCommandPayload,',
    '  validateAgentDescriptor,',
    '  validateAgentState',
    "} from '../renderer/core/agent';",
    "import type { Disposable } from '../types/lifecycle';",
    'import type {',
    '  AgentActiveSessionRegistrationDto,',
    '  AgentApprovalResultRegistrationDto,',
    '  AgentCommandMapRegistrationDto,',
    '  AgentCommandPayloadDto,',
    '  AgentCommandValuesRegistrationDto,',
    '  AgentCompactionRegistrationDto,',
    '  AgentDescriptorDto,',
    '  AgentDescriptorRegistrationDto,',
    '  AgentMessageDto,',
    '  AgentMessageRegistrationDto,',
    '  AgentModelCapabilitiesRegistrationDto,',
    '  AgentObservedStatePatchDto,',
    '  AgentPhaseDto,',
    '  AgentSessionStatusDto,',
    '  AgentStateChangeEvent,',
    '  AgentStateDto,',
    '  AgentStateHandle,',
    '  AgentStatePatchDto,',
    '  AgentStatePatchOperationDto,',
    '  AgentStateRegistrationDto,',
    '  AgentStateSnapshot,',
    '  AgentStateStoreContract,',
    '  AgentStateStoreErrorEvent,',
    '  AgentStateStoreOptions,',
    '  AgentStateUpdateResultDto',
    "} from '../types/agent';",
    "import type { AgentDescriptorDto as ContributionAgentDescriptorDto } from '../types/contributions';",
    "import type { RendererPlatform } from '../types/renderer-platform';",
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    'type AssertFalse<Value extends false> = Value;',
    'type AssertTrue<Value extends true> = Value;',
    'type Equal<Left, Right> = (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2)',
    '    ? (<Value>() => Value extends Right ? 1 : 2) extends',
    '      (<Value>() => Value extends Left ? 1 : 2) ? true : false',
    '    : false;',
    'type ValueOf<Value> = Value[keyof Value];',
    'type IsUnknown<Value> = IsAny<Value> extends true',
    '  ? false',
    '  : unknown extends Value',
    '    ? keyof Value extends never ? true : false',
    '    : false;',
    'const phase: AgentPhaseDto = AgentPhase.READY;',
    'const status: AgentSessionStatusDto = AgentSessionStatus.WAITING_APPROVAL;',
    '// @ts-expect-error Frozen phase constants are readonly literals.',
    "AgentPhase.READY = 'idle';",
    'const commands: AgentCommandMapRegistrationDto = {',
    "  create: 'acme.agent.create', select: 'acme.agent.select', delete: 'acme.agent.delete',",
    "  send: 'acme.agent.send', cancel: 'acme.agent.cancel', approve: 'acme.agent.approve',",
    "  reject: 'acme.agent.reject', preferences: 'acme.agent.preferences', configure: 'acme.agent.configure'",
    '};',
    'const descriptorInput: AgentDescriptorRegistrationDto = {',
    "  id: 'acme.agent.main', title: 'Agent', description: null, commands,",
    '  capabilities: { modes: null, reasoningEfforts: null, accessModes: null }',
    '};',
    "const descriptor: AgentDescriptorDto = validateAgentDescriptor(descriptorInput, 'acme.agent');",
    'const descriptorDescription: string = descriptor.description;',
    '// @ts-expect-error A normalized descriptor contains every defaulted field.',
    "const incompleteDescriptor: AgentDescriptorDto = { id: 'acme.agent.main', title: 'Agent', commands, capabilities: { modes: [], reasoningEfforts: [], accessModes: [], skills: false, localTools: false } };",
    '// @ts-expect-error Normalized descriptors are immutable.',
    'descriptor.order = 10;',
    'const sparseCapabilities: AgentModelCapabilitiesRegistrationDto = {};',
    'const sparseCompaction: AgentCompactionRegistrationDto = {};',
    'const stateInput: AgentStateRegistrationDto = {',
    "  phase: 'ready', message: null, activeSessionId: 'session-1',",
    "  sessions: [{ id: 'session-1', title: 'Session', updatedAt: null }],",
    "  models: [{ ref: 'chat:model', name: 'Model', provider: null, capabilities: sparseCapabilities }],",
    "  skills: [{ id: 'skill-1', name: 'Skill', description: null, revision: null }],",
    '  activeSession: {',
    "    id: 'session-1', title: 'Session', modelRef: null,",
    "    messages: [{ id: 'message-1', role: 'user', content: null }],",
    "    timeline: [{ id: 'timeline-1', title: 'Started', detail: null }],",
    '    compaction: sparseCompaction',
    '  }',
    '};',
    'const state: AgentStateDto = validateAgentState(stateInput);',
    'const normalizedMessage: string = state.activeSession!.messages[0]!.content;',
    'const normalizedLimit: number | null = state.models[0]!.capabilities!.requestOutputLimitTokens;',
    '// @ts-expect-error A normalized state contains its active-session field even when empty.',
    "const incompleteState: AgentStateDto = { phase: 'ready', message: '', activeSessionId: '', sessions: [], models: [], skills: [] };",
    '// @ts-expect-error Normalized state arrays are immutable.',
    "state.sessions.push({ id: 'other', title: 'Other', updatedAt: '', status: 'idle', mode: 'chat' });",
    '// @ts-expect-error Agent phases are a closed host protocol.',
    "const invalidPhase: AgentStateRegistrationDto = { phase: 'pending' };",
    '// @ts-expect-error Agent modes are closed.',
    "const invalidMode: AgentDescriptorRegistrationDto = { id: 'acme.agent.main', title: 'Agent', commands, capabilities: { modes: ['plan'] } };",
    '// @ts-expect-error Session statuses are closed.',
    "const invalidStatus: AgentStateRegistrationDto = { sessions: [{ id: 'session-1', title: 'Session', status: 'waiting' }] };",
    '// @ts-expect-error Message roles cannot introduce executable tool messages.',
    "const invalidRole: AgentMessageRegistrationDto = { id: 'message-1', role: 'tool' };",
    '// @ts-expect-error Reasoning efforts are closed.',
    "const invalidEffort: AgentActiveSessionRegistrationDto = { id: 'session-1', title: 'Session', reasoningEffort: 'ultra' };",
    '// @ts-expect-error Effective reasoning efforts are closed.',
    "const invalidEffectiveEffort: AgentActiveSessionRegistrationDto = { id: 'session-1', title: 'Session', effectiveReasoningEffort: 'auto' };",
    '// @ts-expect-error Access modes cannot bypass the host-owned policy.',
    "const invalidAccess: AgentActiveSessionRegistrationDto = { id: 'session-1', title: 'Session', accessMode: 'unsafe' };",
    '// @ts-expect-error Timeline kinds are semantic host tokens.',
    "const invalidTimelineKind: AgentStateRegistrationDto = { activeSession: { id: 'session-1', title: 'Session', timeline: [{ id: 'timeline-1', title: 'Unsafe', kind: 'html' }] } };",
    '// @ts-expect-error Timeline statuses are closed.',
    "const invalidTimelineStatus: AgentStateRegistrationDto = { activeSession: { id: 'session-1', title: 'Session', timeline: [{ id: 'timeline-1', title: 'Unsafe', status: 'unknown' }] } };",
    '// @ts-expect-error Goal statuses are closed.',
    "const invalidGoalStatus: AgentStateRegistrationDto = { activeSession: { id: 'session-1', title: 'Session', goal: { title: 'Goal', status: 'paused' } } };",
    '// @ts-expect-error Approval tools are a closed host-owned set.',
    "const invalidApprovalTool: AgentApprovalResultRegistrationDto = { tool: 'shell' };",
    '// @ts-expect-error Approval outcomes preserve only the two execution-certainty states.',
    "const invalidApprovalOutcome: AgentApprovalResultRegistrationDto = { outcome: 'executed' };",
    "const stateMerge: AgentStatePatchOperationDto = { type: 'state.merge', value: { message: 'Working' } };",
    "const sessionMerge: AgentStatePatchOperationDto = { type: 'session.merge', value: { status: 'running' } };",
    'const messageUpsert: AgentStatePatchOperationDto = {',
    "  type: 'message.upsert', value: { id: 'message-2', role: 'assistant', content: 'Working' }",
    '};',
    'const timelineUpsert: AgentStatePatchOperationDto = {',
    "  type: 'timeline.upsert', value: { id: 'timeline-2', title: 'Working', status: 'running' }",
    '};',
    'const patch: AgentStatePatchDto = {',
    '  baseVersion: 1, operations: [stateMerge, sessionMerge, messageUpsert, timelineUpsert]',
    '};',
    'const patched: AgentStateDto = applyAgentStatePatch(state, patch);',
    '// @ts-expect-error Patch operation types are closed.',
    "const unknownOperation: AgentStatePatchOperationDto = { type: 'session.delete', value: {} };",
    '// @ts-expect-error Top-level merges cannot replace the active-session object.',
    "const stateMergeWithSession: AgentStatePatchOperationDto = { type: 'state.merge', value: { activeSession: null } };",
    '// @ts-expect-error Session merges cannot replace bounded message arrays.',
    "const sessionMergeWithMessages: AgentStatePatchOperationDto = { type: 'session.merge', value: { messages: [] } };",
    '// @ts-expect-error Message patch values retain the closed role union.',
    "const messageWithInvalidRole: AgentStatePatchOperationDto = { type: 'message.upsert', value: { id: 'message-3', role: 'tool' } };",
    'const commandValues: AgentCommandValuesRegistrationDto = {',
    "  sessionId: null, text: 'Prompt', mode: 'goal', reasoningEffort: 'xhigh', accessMode: 'auto',",
    "  modelRef: null, skillIds: ['skill-1'], approvalId: null",
    '};',
    "const payload: AgentCommandPayloadDto = createAgentCommandPayload('acme.agent.main', 'customAction', commandValues);",
    '// @ts-expect-error Published command payloads are immutable.',
    "payload.action = 'send';",
    'declare const change: AgentStateChangeEvent;',
    "if (change.type === 'added' || change.type === 'removed') {",
    '  const noPatch: null = change.patch;',
    '  void noPatch;',
    '} else {',
    '  const observedPatch: AgentObservedStatePatchDto | null = change.patch;',
    '  if (change.patch) {',
    '    const patchedState: AgentStateDto = change.record.state;',
    '    const observedOperation = change.patch.operations[0]!;',
    "    if (observedOperation.type === 'message.upsert') {",
    '      const observedMessage: AgentMessageDto = observedOperation.value;',
    '      void observedMessage;',
    '    }',
    '    // @ts-expect-error Observed operation arrays are immutable.',
    '    change.patch.operations.push(change.patch.operations[0]!);',
    '  }',
    '}',
    'const storeOptions: AgentStateStoreOptions = {',
    '  onError(event: AgentStateStoreErrorEvent) {',
    "    const source: 'agent-state-listener' = event.source;",
    '    // @ts-expect-error Listener failures remain unknown until narrowed.',
    '    event.error.message;',
    '    void source;',
    '  }',
    '};',
    'const store: AgentStateStoreContract = new AgentStateStore(storeOptions);',
    "const handle: AgentStateHandle = store.register(descriptorInput, { owner: 'acme.agent' });",
    'const handleDisposable: Disposable = handle;',
    'const version = handle.setState(stateInput);',
    'const update: AgentStateUpdateResultDto = handle.updateState(patch);',
    'if (update.applied) { const applied: true = update.applied; void applied; }',
    'else { const rejected: false = update.applied; void rejected; }',
    'const subscription: Disposable = store.onDidChange(() => {});',
    'const snapshots: readonly AgentStateSnapshot[] = store.list();',
    "const snapshot: AgentStateSnapshot | null = store.get('acme.agent.main');",
    'declare const platform: RendererPlatform;',
    'const platformAgents: AgentStateStoreContract = platform.agents;',
    'declare const unknownValue: unknown;',
    'const descriptorFromUnknown: AgentDescriptorDto = validateAgentDescriptor(unknownValue);',
    'const stateFromUnknown: AgentStateDto = validateAgentState(unknownValue);',
    'type PhaseConstantsMatch = AssertTrue<Equal<ValueOf<typeof AgentPhase>, AgentPhaseDto>>;',
    'type StatusConstantsMatch = AssertTrue<Equal<ValueOf<typeof AgentSessionStatus>, AgentSessionStatusDto>>;',
    'type ContributionDescriptorMatches = AssertTrue<Equal<ContributionAgentDescriptorDto, AgentDescriptorDto>>;',
    "type PlatformUsesStoreContract = AssertTrue<Equal<RendererPlatform['agents'], AgentStateStoreContract>>;",
    'type DescriptorReturnIsNotAny = AssertFalse<IsAny<ReturnType<typeof validateAgentDescriptor>>>;',
    'type StateReturnIsNotAny = AssertFalse<IsAny<ReturnType<typeof validateAgentState>>>;',
    'type PatchReturnIsNotAny = AssertFalse<IsAny<ReturnType<typeof applyAgentStatePatch>>>;',
    'type PayloadReturnIsNotAny = AssertFalse<IsAny<ReturnType<typeof createAgentCommandPayload>>>;',
    "type SnapshotStateIsNotAny = AssertFalse<IsAny<AgentStateSnapshot['state']>>;",
    "type EventPatchIsNotAny = AssertFalse<IsAny<AgentStateChangeEvent['patch']>>;",
    "type StoreErrorIsUnknown = AssertTrue<IsUnknown<AgentStateStoreErrorEvent['error']>>;",
    'const normalizedMessageDto: AgentMessageDto = state.activeSession!.messages[0]!;',
    'void phase; void status; void descriptorDescription; void normalizedMessage; void normalizedLimit;',
    'void incompleteDescriptor; void incompleteState; void invalidPhase; void invalidMode; void invalidStatus;',
    'void invalidRole; void invalidEffort; void invalidEffectiveEffort; void invalidAccess;',
    'void invalidTimelineKind; void invalidTimelineStatus; void invalidGoalStatus;',
    'void invalidApprovalTool; void invalidApprovalOutcome; void patched; void unknownOperation;',
    'void stateMergeWithSession; void sessionMergeWithMessages; void messageWithInvalidRole;',
    'void payload; void storeOptions; void handleDisposable; void version; void update;',
    'void subscription; void snapshots; void snapshot; void platformAgents;',
    'void descriptorFromUnknown; void stateFromUnknown; void normalizedMessageDto;',
    'void (null as unknown as PhaseConstantsMatch);',
    'void (null as unknown as StatusConstantsMatch);',
    'void (null as unknown as ContributionDescriptorMatches);',
    'void (null as unknown as PlatformUsesStoreContract);',
    'void (null as unknown as DescriptorReturnIsNotAny);',
    'void (null as unknown as StateReturnIsNotAny);',
    'void (null as unknown as PatchReturnIsNotAny);',
    'void (null as unknown as PayloadReturnIsNotAny);',
    'void (null as unknown as SnapshotStateIsNotAny);',
    'void (null as unknown as EventPatchIsNotAny);',
    'void (null as unknown as StoreErrorIsUnknown);',
    'handle.dispose(); subscription.dispose(); store.dispose();',
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__agent-types-contract.ts',
    source
  });
});
