'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('cache model contracts keep wire data typed, protocol values open, and the pure facade service-free', () => {
  const source = [
    "import * as cacheModel from '../src/cache-model';",
    'import {',
    '  CATEGORY_ORDER,',
    '  HISTORY_STATES,',
    '  SCHEMA_VERSION,',
    '  compareEntries,',
    '  groupInventory,',
    '  isCurrentEnvironmentEntry,',
    '  isServiceCategory,',
    '  normalizeEntry,',
    '  normalizeInventory,',
    '  workspaceMatches',
    "} from '../src/cache-model';",
    'import type {',
    '  CacheCapabilitiesDto,',
    '  CacheCategoryDto,',
    '  CacheEntryDto,',
    '  CacheEntryWireDto,',
    '  CacheGroupInventoryOptionsDto,',
    '  CacheHistoryStateDto,',
    '  CacheHistoryStatesDto,',
    '  CacheInventoryDto,',
    '  CacheInventoryFilterScopeDto,',
    '  CacheInventoryGroupsDto,',
    '  CacheInventoryProtocolError,',
    '  CacheInventoryWireDto,',
    '  CacheModelFacade,',
    '  CacheProjectNamesDto,',
    '  CacheStateDto,',
    '  CacheWorkspaceContextDto,',
    '  RendererPlatform,',
    '  RendererPluginServiceMap,',
    '  RendererServiceMap',
    "} from '../types/renderer-platform';",
    'type Equal<Left, Right> =',
    '  (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2) ? true : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type AssertFalse<Value extends false> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    "type FacadeKey = 'SCHEMA_VERSION' | 'CATEGORY_ORDER' | 'HISTORY_STATES' | 'normalizeEntry' | 'normalizeInventory' | 'groupInventory' | 'compareEntries' | 'workspaceMatches' | 'isCurrentEnvironmentEntry' | 'isServiceCategory';",
    'type CoreExportsAreExact = AssertTrue<Equal<keyof typeof cacheModel, FacadeKey>>;',
    'type FacadeIsExact = AssertTrue<Equal<keyof CacheModelFacade, FacadeKey>>;',
    'type SchemaIsExact = AssertTrue<Equal<typeof SCHEMA_VERSION, 2>>;',
    'type HistoryStateIsExact = AssertTrue<Equal<CacheHistoryStateDto, \'superseded\' | \'orphaned\' | \'retired\'>>;',
    'type CategoryIsOpen = AssertTrue<Equal<CacheCategoryDto, string>>;',
    'type StateIsOpen = AssertTrue<Equal<CacheStateDto, string>>;',
    'type ScopeIsOpen = AssertTrue<string extends CacheInventoryFilterScopeDto ? true : false>;',
    'type NormalizeEntryReturn = AssertTrue<Equal<ReturnType<typeof normalizeEntry>, CacheEntryDto | null>>;',
    'type NormalizeInventoryReturn = AssertTrue<Equal<ReturnType<typeof normalizeInventory>, CacheInventoryDto>>;',
    'type GroupReturn = AssertTrue<Equal<ReturnType<typeof groupInventory>, CacheInventoryGroupsDto>>;',
    'type CompareReturn = AssertTrue<Equal<ReturnType<typeof compareEntries>, number>>;',
    'type WorkspaceReturn = AssertTrue<Equal<ReturnType<typeof workspaceMatches>, boolean>>;',
    'type EnvironmentReturn = AssertTrue<Equal<ReturnType<typeof isCurrentEnvironmentEntry>, boolean>>;',
    'type ServiceReturn = AssertTrue<Equal<ReturnType<typeof isServiceCategory>, boolean>>;',
    "type NormalizeEntrySignature = AssertTrue<Equal<CacheModelFacade['normalizeEntry'], typeof normalizeEntry>>;",
    "type NormalizeInventorySignature = AssertTrue<Equal<CacheModelFacade['normalizeInventory'], typeof normalizeInventory>>;",
    "type GroupSignature = AssertTrue<Equal<CacheModelFacade['groupInventory'], typeof groupInventory>>;",
    "type CompareSignature = AssertTrue<Equal<CacheModelFacade['compareEntries'], typeof compareEntries>>;",
    "type WorkspaceSignature = AssertTrue<Equal<CacheModelFacade['workspaceMatches'], typeof workspaceMatches>>;",
    "type EnvironmentSignature = AssertTrue<Equal<CacheModelFacade['isCurrentEnvironmentEntry'], typeof isCurrentEnvironmentEntry>>;",
    "type ServiceSignature = AssertTrue<Equal<CacheModelFacade['isServiceCategory'], typeof isServiceCategory>>;",
    'type FacadeIsNotAny = AssertFalse<IsAny<CacheModelFacade>>;',
    'type EntryIsNotAny = AssertFalse<IsAny<CacheEntryDto>>;',
    'type WireEntryIsNotAny = AssertFalse<IsAny<CacheEntryWireDto>>;',
    'type InventoryIsNotAny = AssertFalse<IsAny<CacheInventoryDto>>;',
    'type GroupsAreNotAny = AssertFalse<IsAny<CacheInventoryGroupsDto>>;',
    "type FacadeIsNotDisposable = AssertFalse<'dispose' extends keyof CacheModelFacade ? true : false>;",
    "type WorkbenchServiceAbsent = AssertFalse<'workbench.cacheModel' extends keyof RendererServiceMap ? true : false>;",
    "type PluginServiceAbsent = AssertFalse<'workbench.cacheModel' extends keyof RendererPluginServiceMap ? true : false>;",
    'const schema: 2 = SCHEMA_VERSION;',
    'const categoryOrder: readonly CacheCategoryDto[] = CATEGORY_ORDER;',
    'const historyStates: CacheHistoryStatesDto = HISTORY_STATES;',
    "const futureCategory: CacheCategoryDto = 'future-cache-kind';",
    "const futureState: CacheStateDto = 'future-lifecycle-state';",
    "const futureScope: CacheInventoryFilterScopeDto = 'future-server-scope';",
    "const wireEntry: CacheEntryWireDto = { id: 'id', category: 'results', custom: true };",
    "const wireInventory: CacheInventoryWireDto = { schema: 2, entries: [wireEntry], future_field: 7 };",
    'const options: CacheGroupInventoryOptionsDto = {',
    "  filters: { category: futureCategory, scope: futureScope },",
    "  context: { workspaceId: 'workspace', runtimeId: 'runtime' },",
    "  projectNames: { workspace: 'Workspace' }",
    '};',
    'const context: CacheWorkspaceContextDto = options.context!;',
    'const names: CacheProjectNamesDto = options.projectNames!;',
    'declare const entry: CacheEntryDto;',
    'declare const inventory: CacheInventoryDto;',
    'declare const groups: CacheInventoryGroupsDto;',
    'declare const capabilities: CacheCapabilitiesDto;',
    'declare const facade: CacheModelFacade;',
    'const normalizedEntry: CacheEntryDto | null = facade.normalizeEntry(wireEntry);',
    'const normalizedInventory: CacheInventoryDto = facade.normalizeInventory(wireInventory);',
    'const grouped: CacheInventoryGroupsDto = facade.groupInventory(inventory, options);',
    'facade.CATEGORY_ORDER.push(futureCategory);',
    'facade.CATEGORY_ORDER = [futureCategory];',
    "const protocolCode: 'cache_inventory_protocol_error' = (null as unknown as CacheInventoryProtocolError).code;",
    '// @ts-expect-error Normalized entry DTOs are immutable.',
    "entry.state = 'retired';",
    '// @ts-expect-error Inventory entry collections are immutable.',
    'inventory.entries.push(entry);',
    '// @ts-expect-error Group collections are immutable.',
    'groups.projects.push(groups.projects[0]!);',
    '// @ts-expect-error Capability snapshots are readonly to typed consumers.',
    "capabilities['delete'] = true;",
    '// @ts-expect-error Project-name snapshots are readonly to typed consumers.',
    "names.workspace = 'Changed';",
    '// @ts-expect-error Wire DTO fields are readonly.',
    "wireEntry.id = 'changed';",
    '// @ts-expect-error Core category order is readonly; only the compatibility copy is mutable.',
    "CATEGORY_ORDER.push('changed');",
    'declare const platform: RendererPlatform;',
    '// @ts-expect-error The pure cache model is not a workbench service.',
    "platform.services.get('workbench.cacheModel');",
    '// @ts-expect-error The pure cache model is not exposed to downloaded plugins.',
    "platform.services.getForPlugin('workbench.cacheModel');",
    'void schema; void categoryOrder; void historyStates; void futureCategory; void futureState; void futureScope;',
    'void wireEntry; void wireInventory; void options; void context; void names; void normalizedEntry;',
    'void normalizedInventory; void grouped; void protocolCode; void platform;',
    'void (false as unknown as CoreExportsAreExact);',
    'void (false as unknown as FacadeIsExact);',
    'void (false as unknown as SchemaIsExact);',
    'void (false as unknown as HistoryStateIsExact);',
    'void (false as unknown as CategoryIsOpen);',
    'void (false as unknown as StateIsOpen);',
    'void (false as unknown as ScopeIsOpen);',
    'void (false as unknown as NormalizeEntryReturn);',
    'void (false as unknown as NormalizeInventoryReturn);',
    'void (false as unknown as GroupReturn);',
    'void (false as unknown as CompareReturn);',
    'void (false as unknown as WorkspaceReturn);',
    'void (false as unknown as EnvironmentReturn);',
    'void (false as unknown as ServiceReturn);',
    'void (false as unknown as NormalizeEntrySignature);',
    'void (false as unknown as NormalizeInventorySignature);',
    'void (false as unknown as GroupSignature);',
    'void (false as unknown as CompareSignature);',
    'void (false as unknown as WorkspaceSignature);',
    'void (false as unknown as EnvironmentSignature);',
    'void (false as unknown as ServiceSignature);',
    'void (false as unknown as FacadeIsNotAny);',
    'void (false as unknown as EntryIsNotAny);',
    'void (false as unknown as WireEntryIsNotAny);',
    'void (false as unknown as InventoryIsNotAny);',
    'void (false as unknown as GroupsAreNotAny);',
    'void (false as unknown as FacadeIsNotDisposable);',
    'void (false as unknown as WorkbenchServiceAbsent);',
    'void (false as unknown as PluginServiceAbsent);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__cache-model-types-contract.ts',
    source
  });
});
