'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('cache store contracts separate the writable facade from the private disposable service', () => {
  const source = [
    "import * as cacheStoreCore from '../src/cache-store';",
    'import {',
    '  CACHE_STORE_SERVICE_ID,',
    '  createCacheStoreService,',
    '  extractCacheEntry,',
    '  extractCacheInventory,',
    '  extractData',
    "} from '../src/cache-store';",
    "import type { Disposable, Dispose } from '../types/lifecycle';",
    'import type {',
    '  CacheStoreAbortController,',
    '  CacheStoreActionDto,',
    '  CacheStoreClearRequestDto,',
    '  CacheStoreClearScopeDto,',
    '  CacheStoreClearScopeRequestDto,',
    '  CacheStoreDependencies,',
    '  CacheStoreDeleteRequestDto,',
    '  CacheStoreEntryRequestDto,',
    '  CacheStoreEntryTransportOptions,',
    '  CacheStoreFacade,',
    '  CacheStoreFactoryFacade,',
    '  CacheStoreIdentityUserDto,',
    '  CacheStoreInvalidationDto,',
    '  CacheStoreInventoryRequestDto,',
    '  CacheStoreInventoryTransportOptions,',
    '  CacheStoreListener,',
    '  CacheStoreLoadOptionsDto,',
    '  CacheStoreModel,',
    '  CacheStoreMutationMapDto,',
    '  CacheStoreMutationTransportOptions,',
    '  CacheStoreOperations,',
    '  CacheStoreRendererState,',
    '  CacheStoreRequestMap,',
    '  CacheStoreResponseEnvelopeDto,',
    '  CacheStoreSendToServer,',
    '  CacheStoreService,',
    '  CacheStoreSnapshotDto,',
    '  CacheStoreStatusDto,',
    '  CacheStoreTransportOptions,',
    '  CacheStoreTransportOptionsMap,',
    '  LegacyCacheStoreFactoryOptions',
    "} from '../types/cache-store';",
    'import type {',
    '  CacheEntryDto,',
    '  CacheInventoryDto,',
    '  RendererPlatform,',
    '  RendererPluginServiceMap,',
    '  RendererServiceMap',
    "} from '../types/renderer-platform';",
    'type Equal<Left, Right> =',
    '  (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2) ? true : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type AssertFalse<Value extends false> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    "type CoreExportKey = 'CACHE_STORE_SERVICE_ID' | 'createCacheStoreService' | 'extractData' | 'extractCacheInventory' | 'extractCacheEntry';",
    "type OperationKey = 'subscribe' | 'getState' | 'load' | 'getEntry' | 'deleteEntry' | 'clearScope' | 'invalidate' | 'setActive' | 'reset';",
    "type ServiceKey = OperationKey | 'disposed' | 'dispose';",
    "type FactoryKey = 'createCacheStore' | 'extractData' | 'extractCacheInventory' | 'extractCacheEntry';",
    "type DependencyKey = 'model' | 'getState' | 'sendToServer' | 'createAbortController' | 'dispatchInvalidationEvent' | 'reportListenerError';",
    "type SnapshotKey = 'status' | 'inventory' | 'error' | 'stale' | 'identity' | 'mutations' | 'invalidation';",
    "type CoreExportsAreExact = AssertTrue<Equal<keyof typeof cacheStoreCore, CoreExportKey>>;",
    "type StatusIsExact = AssertTrue<Equal<CacheStoreStatusDto, 'idle' | 'loading' | 'refreshing' | 'ready' | 'error'>>;",
    "type ActionIsExact = AssertTrue<Equal<CacheStoreActionDto, 'getCacheInventory' | 'getCacheEntry' | 'deleteCacheEntry' | 'clearCacheScope'>>;",
    "type ClearScopeIsExact = AssertTrue<Equal<CacheStoreClearScopeDto, 'owner' | 'workspace' | 'shared'>>;",
    'type RequestActionsAreExact = AssertTrue<Equal<keyof CacheStoreRequestMap, CacheStoreActionDto>>;',
    'type TransportActionsAreExact = AssertTrue<Equal<keyof CacheStoreTransportOptionsMap, CacheStoreActionDto>>;',
    "type EntryRequestIsExact = AssertTrue<Equal<keyof CacheStoreEntryRequestDto, 'cacheId'>>;",
    "type DeleteRequestIsExact = AssertTrue<Equal<keyof CacheStoreDeleteRequestDto, 'cacheId' | 'expectedRevision'>>;",
    "type ClearRequestIsExact = AssertTrue<Equal<keyof CacheStoreClearRequestDto, 'scope' | 'expectedRevision' | 'workspaceId' | 'category'>>;",
    "type InventoryTimeoutIsExact = AssertTrue<Equal<CacheStoreInventoryTransportOptions['timeoutMs'], 20000>>;",
    "type EntryTimeoutIsExact = AssertTrue<Equal<CacheStoreEntryTransportOptions['timeoutMs'], 20000>>;",
    "type MutationTimeoutIsExact = AssertTrue<Equal<CacheStoreMutationTransportOptions['timeoutMs'], 30000>>;",
    'type OperationsAreExact = AssertTrue<Equal<keyof CacheStoreOperations, OperationKey>>;',
    'type FacadeIsExact = AssertTrue<Equal<keyof CacheStoreFacade, OperationKey>>;',
    'type ServiceIsExact = AssertTrue<Equal<keyof CacheStoreService, ServiceKey>>;',
    'type FactoryIsExact = AssertTrue<Equal<keyof CacheStoreFactoryFacade, FactoryKey>>;',
    'type DependenciesAreExact = AssertTrue<Equal<keyof CacheStoreDependencies, DependencyKey>>;',
    'type SnapshotIsExact = AssertTrue<Equal<keyof CacheStoreSnapshotDto, SnapshotKey>>;',
    "type ModelIsExact = AssertTrue<Equal<keyof CacheStoreModel, 'normalizeEntry' | 'normalizeInventory'>>;",
    "type SubscribeReturn = AssertTrue<Equal<ReturnType<CacheStoreFacade['subscribe']>, Dispose>>;",
    "type StateReturn = AssertTrue<Equal<ReturnType<CacheStoreFacade['getState']>, CacheStoreSnapshotDto>>;",
    "type LoadReturn = AssertTrue<Equal<ReturnType<CacheStoreFacade['load']>, Promise<CacheInventoryDto | null>>>;",
    "type EntryReturn = AssertTrue<Equal<ReturnType<CacheStoreFacade['getEntry']>, Promise<CacheEntryDto | null>>>;",
    "type ResetReturn = AssertTrue<Equal<ReturnType<CacheStoreFacade['reset']>, void>>;",
    'type FactoryIsNotAny = AssertFalse<IsAny<CacheStoreFactoryFacade>>;',
    'type ServiceIsNotAny = AssertFalse<IsAny<CacheStoreService>>;',
    'type StateIsNotAny = AssertFalse<IsAny<CacheStoreSnapshotDto>>;',
    'type InvalidationIsNotAny = AssertFalse<IsAny<CacheStoreInvalidationDto>>;',
    "type PluginServiceAbsent = AssertFalse<'workbench.cacheStore' extends keyof RendererPluginServiceMap ? true : false>;",
    "const serviceId: 'workbench.cacheStore' = CACHE_STORE_SERVICE_ID;",
    "const action: CacheStoreActionDto = 'getCacheInventory';",
    "const status: CacheStoreStatusDto = 'refreshing';",
    "const clearScope: CacheStoreClearScopeDto = 'workspace';",
    'const loadOptions: CacheStoreLoadOptionsDto = { force: true, future: 1 };',
    "const clearRequest: CacheStoreClearScopeRequestDto = { scope: 'workspace', workspaceId: 'workspace', category: 'dependencies', future: true };",
    "const user: CacheStoreIdentityUserDto = { id: 'user', future: true };",
    "const rendererState: CacheStoreRendererState = { serverSettings: { ip: 'server' }, auth: { token: 'token', user }, future: true };",
    'const controller: CacheStoreAbortController = { signal: {}, abort() {} };',
    'const readTransport: CacheStoreTransportOptions = { quiet: true, timeoutMs: 20000, signal: controller.signal };',
    'const writeTransport: CacheStoreTransportOptions = { quiet: true, timeoutMs: 30000 };',
    'const entryTransport: CacheStoreEntryTransportOptions = { quiet: true, timeoutMs: 20000 };',
    'const inventoryRequest: CacheStoreInventoryRequestDto = {};',
    "const entryRequest: CacheStoreEntryRequestDto = { cacheId: 'entry' };",
    "const deleteRequest: CacheStoreDeleteRequestDto = { cacheId: 'entry', expectedRevision: 'revision' };",
    "const clearPayload: CacheStoreClearRequestDto = { scope: 'workspace', expectedRevision: 'revision', workspaceId: 'workspace' };",
    'const requestMap: CacheStoreRequestMap = {',
    '  getCacheInventory: inventoryRequest,',
    '  getCacheEntry: entryRequest,',
    '  deleteCacheEntry: deleteRequest,',
    '  clearCacheScope: clearPayload',
    '};',
    'declare const transportMap: CacheStoreTransportOptionsMap;',
    'const mutationMap: CacheStoreMutationMapDto = { \'delete:entry\': true };',
    "const envelope: CacheStoreResponseEnvelopeDto = { success: 0, Data: { cacheInventory: {} }, future: Symbol('future') };",
    'const sender: CacheStoreSendToServer = async (_action, _payload, _options) => ({ success: true });',
    'declare const model: CacheStoreModel;',
    'const dependencies: CacheStoreDependencies = {',
    '  model,',
    '  getState: () => rendererState,',
    '  sendToServer: sender,',
    '  createAbortController: () => controller,',
    '  dispatchInvalidationEvent: (_detail) => undefined,',
    '  reportListenerError: (_error) => undefined',
    '};',
    'const service: CacheStoreService = createCacheStoreService(dependencies);',
    'const operations: CacheStoreOperations = service;',
    'const disposable: Disposable = service;',
    'const registeredService: RendererServiceMap[typeof CACHE_STORE_SERVICE_ID] = service;',
    'declare const facade: CacheStoreFacade;',
    'declare const factory: CacheStoreFactoryFacade;',
    'const snapshot: CacheStoreSnapshotDto = facade.getState();',
    'const listener: CacheStoreListener = (value, reason) => { const current: CacheStoreStatusDto = value.status; void current; void reason; };',
    'const remove: Dispose = facade.subscribe(listener);',
    'const legacyOptions: LegacyCacheStoreFactoryOptions = { global: {}, BOBO: {}, model, future: true };',
    'const legacyStore: CacheStoreFacade = factory.createCacheStore(legacyOptions);',
    'const extractedData: Record<string, unknown> = extractData({ data: {} });',
    'const extractedInventory: unknown | null = extractCacheInventory({});',
    'const extractedEntry: unknown | null = extractCacheEntry({});',
    'const invalidation: CacheStoreInvalidationDto = { reason: \'external\', future: true };',
    "facade.invalidate(invalidation); facade.setActive(true); facade.clearScope(clearRequest); facade.getEntry('id');",
    '// @ts-expect-error Compatibility consumers cannot invoke registry-owned disposal.',
    'facade.dispose();',
    '// @ts-expect-error Compatibility consumers cannot inspect registry-owned disposal state.',
    'facade.disposed;',
    '// @ts-expect-error The typed service is not the compatibility factory.',
    'service.createCacheStore();',
    '// @ts-expect-error Service state snapshots are readonly.',
    "snapshot.status = 'idle';",
    '// @ts-expect-error Mutation snapshots are readonly.',
    "snapshot.mutations['delete:id'] = true;",
    '// @ts-expect-error Transport timeouts are fixed by the cache protocol.',
    'const invalidTimeout: CacheStoreTransportOptions = { quiet: true, timeoutMs: 1000 };',
    '// @ts-expect-error Write requests intentionally carry no AbortSignal.',
    'const invalidWriteSignal: CacheStoreMutationTransportOptions = { quiet: true, timeoutMs: 30000, signal: {} };',
    '// @ts-expect-error Entry requests intentionally carry no AbortSignal.',
    'const invalidEntrySignal: CacheStoreEntryTransportOptions = { quiet: true, timeoutMs: 20000, signal: {} };',
    '// @ts-expect-error Cache actions are a closed transport set.',
    "const invalidAction: CacheStoreActionDto = 'futureCacheAction';",
    '// @ts-expect-error Clear scopes are the closed server protocol set.',
    "const invalidScope: CacheStoreClearScopeDto = 'future-server-scope';",
    '// @ts-expect-error Typed clear requests always identify their scope.',
    'const missingScope: CacheStoreClearScopeRequestDto = { workspaceId: \'workspace\' };',
    '// @ts-expect-error Inventory requests carry no payload fields.',
    'const invalidInventoryRequest: CacheStoreInventoryRequestDto = { future: true };',
    '// @ts-expect-error Transport envelopes are immutable once received.',
    'envelope.success = false;',
    '// @ts-expect-error The cache store is private to the trusted workbench.',
    "(null as unknown as RendererPlatform).services.getForPlugin('workbench.cacheStore');",
    'const fromRegistry: CacheStoreService = (null as unknown as RendererPlatform).services.require(CACHE_STORE_SERVICE_ID);',
    'remove(); disposable.dispose(); legacyStore.reset();',
    'void serviceId; void action; void status; void clearScope; void loadOptions; void clearRequest;',
    'void readTransport; void writeTransport; void entryTransport; void requestMap; void transportMap; void mutationMap; void envelope;',
    'void operations; void registeredService; void snapshot;',
    'void legacyOptions; void extractedData; void extractedInventory; void extractedEntry; void fromRegistry;',
    'void invalidTimeout; void invalidWriteSignal; void invalidEntrySignal; void invalidAction; void invalidScope;',
    'void missingScope; void invalidInventoryRequest;',
    'void (false as unknown as CoreExportsAreExact);',
    'void (false as unknown as StatusIsExact);',
    'void (false as unknown as ActionIsExact);',
    'void (false as unknown as ClearScopeIsExact);',
    'void (false as unknown as RequestActionsAreExact);',
    'void (false as unknown as TransportActionsAreExact);',
    'void (false as unknown as EntryRequestIsExact);',
    'void (false as unknown as DeleteRequestIsExact);',
    'void (false as unknown as ClearRequestIsExact);',
    'void (false as unknown as InventoryTimeoutIsExact);',
    'void (false as unknown as EntryTimeoutIsExact);',
    'void (false as unknown as MutationTimeoutIsExact);',
    'void (false as unknown as OperationsAreExact);',
    'void (false as unknown as FacadeIsExact);',
    'void (false as unknown as ServiceIsExact);',
    'void (false as unknown as FactoryIsExact);',
    'void (false as unknown as DependenciesAreExact);',
    'void (false as unknown as SnapshotIsExact);',
    'void (false as unknown as ModelIsExact);',
    'void (false as unknown as SubscribeReturn);',
    'void (false as unknown as StateReturn);',
    'void (false as unknown as LoadReturn);',
    'void (false as unknown as EntryReturn);',
    'void (false as unknown as ResetReturn);',
    'void (false as unknown as FactoryIsNotAny);',
    'void (false as unknown as ServiceIsNotAny);',
    'void (false as unknown as StateIsNotAny);',
    'void (false as unknown as InvalidationIsNotAny);',
    'void (false as unknown as PluginServiceAbsent);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__cache-store-types-contract.ts',
    source
  });
});
