'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('cache center contracts keep the compatibility facade exact and the disposable service private', () => {
  const source = [
    "import * as cacheCenter from '../src/cache-center';",
    "import { CACHE_CENTER_SERVICE_ID, createCacheCenterService } from '../src/cache-center';",
    "import type { Disposable } from '../types/lifecycle';",
    'import type {',
    '  CacheCenterDependencies,',
    '  CacheCenterFacade,',
    '  CacheCenterFilterScopeDto,',
    '  CacheCenterFiltersDto,',
    '  CacheCenterRendererState,',
    '  CacheCenterService,',
    '  CacheInventoryDto,',
    '  CacheProjectNamesDto,',
    '  RendererPlatform,',
    '  RendererPluginServiceMap,',
    '  RendererServiceMap',
    "} from '../types/renderer-platform';",
    'type Equal<Left, Right> =',
    '  (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2) ? true : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type AssertFalse<Value extends false> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    "type FacadeKey = 'init' | 'load' | 'render' | 'setVisible' | 'setProjectNames' | 'dispose' | 'getFilters';",
    "type DependencyKey = 'document' | 'languageEvents' | 'state' | 'model' | 'getStore' | 'projectKey' | 'getI18n' | 'getIcons' | 'getToast' | 'getConfirm' | 'getProjects' | 'getWorkbench' | 'getPackageCenter' | 'alert';",
    "type CoreExport = 'CACHE_CENTER_SERVICE_ID' | 'createCacheCenterService';",
    'type CoreExportsAreExact = AssertTrue<Equal<keyof typeof cacheCenter, CoreExport>>;',
    'type FacadeIsExact = AssertTrue<Equal<keyof CacheCenterFacade, FacadeKey>>;',
    "type ServiceIsExact = AssertTrue<Equal<keyof CacheCenterService, FacadeKey | 'disposed'>>;",
    'type DependenciesAreExact = AssertTrue<Equal<keyof CacheCenterDependencies, DependencyKey>>;',
    'type ServiceIsDisposable = AssertTrue<CacheCenterService extends Disposable ? true : false>;',
    "type FacadeHidesDisposed = AssertFalse<'disposed' extends keyof CacheCenterFacade ? true : false>;",
    "type ServiceMapEntryIsExact = AssertTrue<Equal<RendererServiceMap['workbench.cacheCenter'], CacheCenterService>>;",
    "type PluginServiceAbsent = AssertFalse<'workbench.cacheCenter' extends keyof RendererPluginServiceMap ? true : false>;",
    'type ServiceIsNotAny = AssertFalse<IsAny<CacheCenterService>>;',
    'type DependenciesAreNotAny = AssertFalse<IsAny<CacheCenterDependencies>>;',
    'type FiltersAreNotAny = AssertFalse<IsAny<CacheCenterFiltersDto>>;',
    "type FilterScopeIsExact = AssertTrue<Equal<CacheCenterFilterScopeDto, 'all' | 'current' | 'shared' | 'services'>>;",
    "type InitResult = AssertTrue<Equal<ReturnType<CacheCenterFacade['init']>, void>>;",
    "type LoadResult = AssertTrue<Equal<ReturnType<CacheCenterFacade['load']>, Promise<CacheInventoryDto | null>>>;",
    "type RenderResult = AssertTrue<Equal<ReturnType<CacheCenterFacade['render']>, void>>;",
    "type FiltersResult = AssertTrue<Equal<ReturnType<CacheCenterFacade['getFilters']>, CacheCenterFiltersDto>>;",
    "const serviceId: 'workbench.cacheCenter' = CACHE_CENTER_SERVICE_ID;",
    'declare const dependencies: CacheCenterDependencies;',
    'const service: CacheCenterService = createCacheCenterService(dependencies);',
    'const disposable: Disposable = service;',
    "const registered: CacheCenterService = (null as unknown as RendererServiceMap)['workbench.cacheCenter'];",
    "const filters: CacheCenterFiltersDto = { scope: 'all', category: 'all' };",
    '// @ts-expect-error Cache-center UI scopes are a closed set.',
    "const futureFilters: CacheCenterFiltersDto = { scope: 'future-server-scope', category: 'future-cache-category' };",
    "const projectNames: CacheProjectNamesDto = { workspace: 'Workspace', __proto__: 'Proto', constructor: 'Constructor' };",
    'const state: CacheCenterRendererState = { workspaceRoot: 7, futureState: true };',
    'service.init();',
    'service.setVisible(true);',
    'service.setProjectNames(projectNames);',
    'service.setProjectNames(null);',
    'service.setProjectNames(undefined);',
    'const loaded: Promise<CacheInventoryDto | null> = service.load({ force: true });',
    'const currentFilters: CacheCenterFiltersDto = service.getFilters();',
    'const currentlyDisposed: boolean = service.disposed;',
    'service.dispose();',
    '// @ts-expect-error Compatibility consumers cannot observe internal lifecycle state.',
    'const facadeDisposed = (service as CacheCenterFacade).disposed;',
    '// @ts-expect-error Filter snapshots are immutable.',
    "filters.scope = 'shared';",
    '// @ts-expect-error Project-name DTOs are immutable.',
    "projectNames.workspace = 'Changed';",
    '// @ts-expect-error Renderer state is immutable to cache-center consumers.',
    "state.workspaceRoot = 'changed';",
    'declare const platform: RendererPlatform;',
    '// @ts-expect-error Cache center is private to the trusted workbench.',
    "platform.services.getForPlugin('workbench.cacheCenter');",
    'void serviceId; void disposable; void registered; void futureFilters; void loaded;',
    'void currentFilters; void currentlyDisposed; void facadeDisposed;',
    'void (false as unknown as CoreExportsAreExact);',
    'void (false as unknown as FacadeIsExact);',
    'void (false as unknown as ServiceIsExact);',
    'void (false as unknown as DependenciesAreExact);',
    'void (false as unknown as ServiceIsDisposable);',
    'void (false as unknown as FacadeHidesDisposed);',
    'void (false as unknown as ServiceMapEntryIsExact);',
    'void (false as unknown as PluginServiceAbsent);',
    'void (false as unknown as ServiceIsNotAny);',
    'void (false as unknown as DependenciesAreNotAny);',
    'void (false as unknown as FiltersAreNotAny);',
    'void (false as unknown as FilterScopeIsExact);',
    'void (false as unknown as InitResult);',
    'void (false as unknown as LoadResult);',
    'void (false as unknown as RenderResult);',
    'void (false as unknown as FiltersResult);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__cache-center-types-contract.ts',
    source
  });
});
