'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('document view contracts separate verified host data, public iframe data, and host-only services', () => {
  const source = [
    "import { validateDocumentViewDescriptor, selectDocumentView } from '../renderer/core/document-view';",
    "import { createSandboxedDocumentView } from '../renderer/core/document-view-sandbox';",
    "import { createDocumentViewService } from '../src/document-views';",
    "import type { Disposable } from '../types/lifecycle';",
    'import type {',
    '  DocumentInfoDto,',
    '  DocumentReadResultDto,',
    '  DocumentViewContributionEntryDto,',
    '  DocumentViewDependencies,',
    '  DocumentViewDescriptorDto,',
    '  DocumentViewDescriptorRegistrationDto,',
    '  DocumentViewHost,',
    '  DocumentViewManifestDescriptorDto,',
    '  DocumentViewPublicDescriptorDto,',
    '  DocumentViewService,',
    '  LoadedDocumentViewDto,',
    '  SandboxedDocumentView,',
    '  SandboxedDocumentViewOptions,',
    '  VerifiedDocumentViewFileDto',
    "} from '../types/document-view';",
    "import type { RendererPlatform, RendererPluginServiceMap, RendererServiceMap } from '../types/renderer-platform';",
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    'type AssertFalse<Value extends false> = Value;',
    'const descriptorInput: DocumentViewDescriptorRegistrationDto = {',
    "  id: 'acme.preview.markdown', title: 'Markdown', extensions: ['.md'], entry: 'dist/view.mjs'",
    '};',
    "const descriptor: DocumentViewDescriptorDto = validateDocumentViewDescriptor(descriptorInput, 'acme.preview');",
    'const normalizedPriority: number = descriptor.priority;',
    'const normalizedResources: readonly string[] = descriptor.resources;',
    'const entry: DocumentViewContributionEntryDto = {',
    "  id: descriptor.id, owner: 'acme.preview', contribution: descriptor",
    '};',
    "const selected: DocumentViewContributionEntryDto | null = selectDocumentView([entry], 'README.MD');",
    'const publicDescriptor: DocumentViewPublicDescriptorDto = {',
    '  id: descriptor.id, title: descriptor.title, extensions: descriptor.extensions, priority: descriptor.priority',
    '};',
    '// @ts-expect-error The iframe descriptor deliberately omits package entry paths.',
    'publicDescriptor.entry;',
    '// @ts-expect-error The iframe descriptor deliberately omits verified package resources.',
    'publicDescriptor.resources;',
    'const verifiedFile: VerifiedDocumentViewFileDto = {',
    "  path: 'dist/view.mjs', source: 'export function activate() {}', hash: 'sha256', mimeType: 'text/javascript'",
    '};',
    'const loaded: LoadedDocumentViewDto = {',
    "  pluginId: 'acme.preview', viewer: { id: descriptor.id, extensions: descriptor.extensions, entry: descriptor.entry, resources: descriptor.resources, priority: descriptor.priority }, entry: verifiedFile, resources: []",
    '};',
    'const manifestDescriptor: DocumentViewManifestDescriptorDto = loaded.viewer;',
    '// @ts-expect-error Main manifest viewers do not promise a localized title.',
    'manifestDescriptor.title;',
    'const documentInfo: DocumentInfoDto = {',
    "  documentId: 'document-1', name: 'README.md', extension: '.md', size: 10, lastModified: '2026-01-01T00:00:00.000Z'",
    '};',
    'const readResult: DocumentReadResultDto = {',
    '  data: new Uint8Array([1, 2, 3]), offset: 0, length: 3, eof: true',
    '};',
    '// @ts-expect-error Document bytes never cross the sandbox contract as text.',
    "const invalidReadResult: DocumentReadResultDto = { data: 'unsafe', offset: 0, length: 6, eof: true };",
    'declare const container: Pick<HTMLElement, \'appendChild\'>;',
    'const sandboxOptions: SandboxedDocumentViewOptions = {',
    '  container, entry: verifiedFile, document: documentInfo, viewer: publicDescriptor,',
    '  read: () => readResult',
    '};',
    'const sandbox: SandboxedDocumentView = createSandboxedDocumentView(sandboxOptions);',
    'const sandboxDisposable: Disposable = sandbox;',
    'declare const dependencies: DocumentViewDependencies;',
    'const service: DocumentViewService = createDocumentViewService(dependencies);',
    'const serviceDisposable: Disposable = service;',
    'declare const platform: RendererPlatform;',
    "const host: Readonly<DocumentViewHost> = platform.services.require('host.documentViews');",
    "const registered: RendererServiceMap['workbench.documentViews'] = service;",
    "const required: DocumentViewService = platform.services.require('workbench.documentViews');",
    "type HostVisible = 'host.documentViews' extends keyof RendererPluginServiceMap ? true : false;",
    "type WorkbenchVisible = 'workbench.documentViews' extends keyof RendererPluginServiceMap ? true : false;",
    'const hostVisible: HostVisible = false;',
    'const workbenchVisible: WorkbenchVisible = false;',
    '// @ts-expect-error The native document broker is host-only.',
    "platform.services.getForPlugin('host.documentViews');",
    '// @ts-expect-error The host-rendered document view service is not exposed to plugin Workers.',
    "platform.services.getForPlugin('workbench.documentViews');",
    "host.loadDocumentView('acme.preview', descriptor.id).then((value: LoadedDocumentViewDto) => void value);",
    "host.readDocument('document-1', 0, 4).then((value: DocumentReadResultDto) => void value);",
    'service.init(); service.find(\'README.md\'); service.hideAll({ restoreEditor: false });',
    'sandboxDisposable.dispose(); serviceDisposable.dispose();',
    'type ValidatorIsNotAny = AssertFalse<IsAny<ReturnType<typeof validateDocumentViewDescriptor>>>;',
    'type SelectorIsNotAny = AssertFalse<IsAny<ReturnType<typeof selectDocumentView>>>;',
    'type ServiceFactoryIsNotAny = AssertFalse<IsAny<ReturnType<typeof createDocumentViewService>>>;',
    'void normalizedPriority; void normalizedResources; void selected; void loaded; void manifestDescriptor;',
    'void invalidReadResult; void registered; void required; void hostVisible; void workbenchVisible;',
    'void (null as unknown as ValidatorIsNotAny);',
    'void (null as unknown as SelectorIsNotAny);',
    'void (null as unknown as ServiceFactoryIsNotAny);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__document-view-types-contract.ts',
    source
  });
});
