'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('environment activity contracts keep scoped events typed and the disposable service private', () => {
  const source = [
    'import {',
    '  createEnvironmentActivityService,',
    '  ENVIRONMENT_ACTIVITY_EVENT_NAME,',
    '  ENVIRONMENT_ACTIVITY_SERVICE_ID,',
    '  ENVIRONMENT_ACTIVITY_STORAGE_KEY,',
    '  stringHash',
    "} from '../src/environment-activity';",
    "import type { Disposable, Dispose } from '../types/lifecycle';",
    'import type {',
    '  EnvironmentActivityActionDto,',
    '  EnvironmentActivityDependencies,',
    '  EnvironmentActivityEventDetailDto,',
    '  EnvironmentActivityEventDto,',
    '  EnvironmentActivityEventKindDto,',
    '  EnvironmentActivityFacade,',
    '  EnvironmentActivityOperations,',
    '  EnvironmentActivityOutcomeDto,',
    '  EnvironmentActivityRecordDetailDto,',
    '  EnvironmentActivityRecordDto,',
    '  EnvironmentActivityScopeDto,',
    '  EnvironmentActivityScopeKeyDto,',
    '  EnvironmentActivityScopeOverridesDto,',
    '  EnvironmentActivityService,',
    '  EnvironmentActivityWorkspaceDto',
    "} from '../types/environment-activity';",
    "import type { RendererPlatform, RendererPluginServiceMap, RendererServiceMap } from '../types/renderer-platform';",
    'type Equal<Left, Right> =',
    '  (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2) ? true : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type AssertFalse<Value extends false> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    "type OperationKey = 'read' | 'record' | 'contextChanged' | 'subscribe' | 'getScope' | 'getScopeKey';",
    "type FacadeKey = OperationKey | '_storageKey';",
    "type ServiceKey = OperationKey | 'disposed' | 'dispose';",
    "type DependencyKey = 'state' | 'storage' | 'projectKey' | 'now' | 'dispatchEvent' | 'reportSubscriberError';",
    "type ActionIsExact = AssertTrue<Equal<EnvironmentActivityActionDto, 'index' | 'install' | 'compile' | 'repair' | 'rebuild'>>;",
    "type EventKindIsExact = AssertTrue<Equal<EnvironmentActivityEventKindDto, EnvironmentActivityActionDto | 'context'>>;",
    "type OutcomeIsExact = AssertTrue<Equal<EnvironmentActivityOutcomeDto, 'completed' | 'failed'>>;",
    'type ScopeKeyShape = AssertTrue<EnvironmentActivityScopeKeyDto extends `e1-${string}` ? true : false>;',
    'type OperationsAreExact = AssertTrue<Equal<keyof EnvironmentActivityOperations, OperationKey>>;',
    'type FacadeIsExact = AssertTrue<Equal<keyof EnvironmentActivityFacade, FacadeKey>>;',
    'type ServiceIsExact = AssertTrue<Equal<keyof EnvironmentActivityService, ServiceKey>>;',
    'type DependenciesAreExact = AssertTrue<Equal<keyof EnvironmentActivityDependencies, DependencyKey>>;',
    "type ReadReturn = AssertTrue<Equal<ReturnType<EnvironmentActivityFacade['read']>, EnvironmentActivityRecordDto>>;",
    "type RecordReturn = AssertTrue<Equal<ReturnType<EnvironmentActivityFacade['record']>, boolean>>;",
    "type ContextReturn = AssertTrue<Equal<ReturnType<EnvironmentActivityFacade['contextChanged']>, void>>;",
    "type SubscribeReturn = AssertTrue<Equal<ReturnType<EnvironmentActivityFacade['subscribe']>, Dispose>>;",
    "type ScopeReturn = AssertTrue<Equal<ReturnType<EnvironmentActivityFacade['getScope']>, EnvironmentActivityScopeDto>>;",
    "type ScopeKeyReturn = AssertTrue<Equal<ReturnType<EnvironmentActivityFacade['getScopeKey']>, EnvironmentActivityScopeKeyDto>>;",
    "type StorageKeyType = AssertTrue<Equal<EnvironmentActivityFacade['_storageKey'], string>>;",
    'type FactoryIsNotAny = AssertFalse<IsAny<ReturnType<typeof createEnvironmentActivityService>>>;',
    'type EventIsNotAny = AssertFalse<IsAny<EnvironmentActivityEventDto>>;',
    'type RecordIsNotAny = AssertFalse<IsAny<EnvironmentActivityRecordDto>>;',
    "type PluginServiceAbsent = AssertFalse<'workbench.environmentActivity' extends keyof RendererPluginServiceMap ? true : false>;",
    "const serviceId: 'workbench.environmentActivity' = ENVIRONMENT_ACTIVITY_SERVICE_ID;",
    "const storageKey: 'bobocloud.environment.activity.v1' = ENVIRONMENT_ACTIVITY_STORAGE_KEY;",
    "const eventName: 'bobo:environment-activity' = ENVIRONMENT_ACTIVITY_EVENT_NAME;",
    "const action: EnvironmentActivityActionDto = 'compile';",
    "const outcome: EnvironmentActivityOutcomeDto = 'completed';",
    "const scopeKey: EnvironmentActivityScopeKeyDto = 'e1-future';",
    "const overrides: EnvironmentActivityScopeOverridesDto = { workspaceRoot: null, language: 'rust', runtime: 'rust:1.90', future: true };",
    "const detail: EnvironmentActivityRecordDetailDto = { at: 10, outcome, scope: overrides, source: 'runner' };",
    "const eventDetail: EnvironmentActivityEventDetailDto = { ...detail, reason: 'changed' };",
    'declare const dependencies: EnvironmentActivityDependencies;',
    'const service: EnvironmentActivityService = createEnvironmentActivityService(dependencies);',
    'const operations: EnvironmentActivityOperations = service;',
    'declare const facade: EnvironmentActivityFacade;',
    'const disposable: Disposable = service;',
    'const registeredService: RendererServiceMap[typeof ENVIRONMENT_ACTIVITY_SERVICE_ID] = service;',
    'const hashed: string = stringHash({ future: true });',
    'const record: EnvironmentActivityRecordDto = facade.read(overrides);',
    "facade._storageKey = 'compatibility-key';",
    'const scope: EnvironmentActivityScopeDto = facade.getScope(overrides);',
    'const workspace: EnvironmentActivityWorkspaceDto = scope.workspace;',
    "const event: EnvironmentActivityEventDto = { kind: 'context', scopeKey, record, detail: eventDetail };",
    'const remove: Dispose = facade.subscribe((value) => { const kind: EnvironmentActivityEventKindDto = value.kind; void kind; });',
    '// @ts-expect-error Compatibility consumers cannot invoke registry-owned disposal.',
    'facade.dispose();',
    '// @ts-expect-error The typed service does not carry the writable compatibility metadata key.',
    'const facadeFromService: EnvironmentActivityFacade = service;',
    '// @ts-expect-error Service consumers do not own compatibility metadata.',
    "service._storageKey = 'compatibility-key';",
    '// @ts-expect-error Action names are a closed protocol set.',
    "facade.record('__proto__', detail);",
    '// @ts-expect-error Scope keys must retain the version prefix.',
    "const invalidScopeKey: EnvironmentActivityScopeKeyDto = 'plain-key';",
    '// @ts-expect-error Record snapshots are readonly.',
    'record.updatedAt = 20;',
    '// @ts-expect-error Event payloads are readonly.',
    "event.kind = 'compile';",
    'if (workspace.kind === \'team\') { const teamId: string = workspace.teamId; void teamId; }',
    'else { const folderKey: string = workspace.folderKey; void folderKey; }',
    'declare const platform: RendererPlatform;',
    'const fromRegistry: EnvironmentActivityService = platform.services.require(ENVIRONMENT_ACTIVITY_SERVICE_ID);',
    '// @ts-expect-error Environment activity is private to the trusted workbench.',
    "platform.services.getForPlugin('workbench.environmentActivity');",
    'remove(); disposable.dispose();',
    'void serviceId; void storageKey; void eventName; void action; void outcome; void scopeKey;',
    'void detail; void event; void operations; void registeredService; void hashed; void fromRegistry;',
    'void invalidScopeKey; void facadeFromService;',
    'void (false as unknown as ActionIsExact);',
    'void (false as unknown as EventKindIsExact);',
    'void (false as unknown as OutcomeIsExact);',
    'void (false as unknown as ScopeKeyShape);',
    'void (false as unknown as OperationsAreExact);',
    'void (false as unknown as FacadeIsExact);',
    'void (false as unknown as ServiceIsExact);',
    'void (false as unknown as DependenciesAreExact);',
    'void (false as unknown as ReadReturn);',
    'void (false as unknown as RecordReturn);',
    'void (false as unknown as ContextReturn);',
    'void (false as unknown as SubscribeReturn);',
    'void (false as unknown as ScopeReturn);',
    'void (false as unknown as ScopeKeyReturn);',
    'void (false as unknown as StorageKeyType);',
    'void (false as unknown as FactoryIsNotAny);',
    'void (false as unknown as EventIsNotAny);',
    'void (false as unknown as RecordIsNotAny);',
    'void (false as unknown as PluginServiceAbsent);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__environment-activity-types-contract.ts',
    source
  });
});
