'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('environment center contracts keep DTOs, host authority, and disposal private and exact', () => {
  const source = [
    "import * as environmentCenter from '../src/environment-center';",
    "import { createEnvironmentCenterService, ENVIRONMENT_CENTER_SERVICE_ID } from '../src/environment-center';",
    "import type { Disposable } from '../types/lifecycle';",
    'import type {',
    '  EnvironmentCenterActionDto,',
    '  EnvironmentCenterDependencies,',
    '  EnvironmentCenterFacade,',
    '  EnvironmentCenterNativeHostPort,',
    '  EnvironmentCenterRefreshOptionsDto,',
    '  EnvironmentCenterServerRequestMap,',
    '  EnvironmentCenterServerResponseMap,',
    '  EnvironmentCenterService,',
    '  ProjectEnvironmentActionDto,',
    '  ProjectEnvironmentActionRequestDto,',
    '  ProjectEnvironmentActionResultDto,',
    '  ProjectEnvironmentRepairPlanDto,',
    '  ProjectEnvironmentRequestContextDto,',
    '  ProjectEnvironmentSnapshotDto,',
    '  ProjectEnvironmentWireDto,',
    '  RendererPlatform,',
    '  RendererPluginServiceMap,',
    '  RendererServiceMap',
    "} from '../types/renderer-platform';",
    'type Equal<Left, Right> =',
    '  (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2) ? true : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type AssertFalse<Value extends false> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    "type FacadeKey = 'init' | 'refresh' | 'scheduleRefresh' | 'runAction' | 'getSnapshot' | 'getRequestContext' | 'dispose';",
    "type DependencyKey = 'document' | 'events' | 'state' | 'getNativeHost' | 'getI18n' | 'getLsp' | 'getEnvironmentActivity' | 'getTaskProblemMatcher' | 'getWorkspace' | 'getPackageCenter' | 'getWorkbench' | 'getToast' | 'getConfirm' | 'projectKey' | 'getMarkerPort' | 'sendToServer' | 'setTimer' | 'clearTimer' | 'now';",
    "type CoreExport = 'ENVIRONMENT_CENTER_SERVICE_ID' | 'createEnvironmentCenterService' | 'canonicalLanguage' | 'dependencyIssueRows' | 'healthFallbackDetail' | 'languageMatchesRuntime' | 'localizedDependencyReason' | 'localizedDynamicText' | 'mergeLiveDependencyDiagnostics' | 'mergeServerSnapshot' | 'normalizeHealth' | 'packageIdentity' | 'recognizeManifests' | 'unresolvedPythonImport';",
    "type ServerAction = 'getProjectEnvironment' | 'planProjectEnvironmentRepair' | 'applyProjectEnvironmentAction';",
    'type CoreExportsAreExact = AssertTrue<Equal<keyof typeof environmentCenter, CoreExport>>;',
    'type FacadeIsExact = AssertTrue<Equal<keyof EnvironmentCenterFacade, FacadeKey>>;',
    "type ServiceIsExact = AssertTrue<Equal<keyof EnvironmentCenterService, FacadeKey | 'disposed'>>;",
    'type DependenciesAreExact = AssertTrue<Equal<keyof EnvironmentCenterDependencies, DependencyKey>>;',
    'type ServerActionsAreExact = AssertTrue<Equal<keyof EnvironmentCenterServerRequestMap, ServerAction>>;',
    "type EnvironmentResponseContractIsExact = AssertTrue<Equal<EnvironmentCenterServerResponseMap['getProjectEnvironment']['data'], ProjectEnvironmentWireDto | undefined>>;",
    "type PlanResponseContractIsExact = AssertTrue<Equal<EnvironmentCenterServerResponseMap['planProjectEnvironmentRepair']['data'], ProjectEnvironmentRepairPlanDto | undefined>>;",
    "type ApplyResponseContractIsExact = AssertTrue<Equal<EnvironmentCenterServerResponseMap['applyProjectEnvironmentAction']['data'], ProjectEnvironmentActionResultDto | undefined>>;",
    "type WireHidesRendererSource = AssertFalse<'source' extends keyof ProjectEnvironmentWireDto ? true : false>;",
    "type CenterActionsAreExact = AssertTrue<Equal<EnvironmentCenterActionDto, 'repair' | 'rebuild' | 'refresh' | 'clear'>>;",
    "type ServerActionsPayloadAreExact = AssertTrue<Equal<ProjectEnvironmentActionDto, 'repair' | 'rebuild' | 'clearCache'>>;",
    'type ServiceIsDisposable = AssertTrue<EnvironmentCenterService extends Disposable ? true : false>;',
    "type FacadeHidesDisposed = AssertFalse<'disposed' extends keyof EnvironmentCenterFacade ? true : false>;",
    "type WorkbenchServiceIsExact = AssertTrue<Equal<RendererServiceMap['workbench.environmentCenter'], EnvironmentCenterService>>;",
    "type HostServiceIsExact = AssertTrue<Equal<RendererServiceMap['host.environmentCenter'], Readonly<EnvironmentCenterNativeHostPort>>>;",
    "type WorkbenchPluginServiceAbsent = AssertFalse<'workbench.environmentCenter' extends keyof RendererPluginServiceMap ? true : false>;",
    "type HostPluginServiceAbsent = AssertFalse<'host.environmentCenter' extends keyof RendererPluginServiceMap ? true : false>;",
    'type ServiceIsNotAny = AssertFalse<IsAny<EnvironmentCenterService>>;',
    'type SnapshotIsNotAny = AssertFalse<IsAny<ProjectEnvironmentSnapshotDto>>;',
    "type WireHasNoRendererSource = AssertFalse<'source' extends keyof ProjectEnvironmentWireDto ? true : false>;",
    "type WireCheckedAtIsExact = AssertTrue<Equal<ProjectEnvironmentWireDto['checkedAt'], number>>;",
    "type EnvironmentResponseIsExact = AssertTrue<Equal<EnvironmentCenterServerResponseMap['getProjectEnvironment']['data'], ProjectEnvironmentWireDto | undefined>>;",
    "type PlanResponseIsExact = AssertTrue<Equal<EnvironmentCenterServerResponseMap['planProjectEnvironmentRepair']['data'], ProjectEnvironmentRepairPlanDto | undefined>>;",
    "type ApplyResponseIsExact = AssertTrue<Equal<EnvironmentCenterServerResponseMap['applyProjectEnvironmentAction']['data'], ProjectEnvironmentActionResultDto | undefined>>;",
    "type RefreshResult = AssertTrue<Equal<ReturnType<EnvironmentCenterFacade['refresh']>, Promise<ProjectEnvironmentSnapshotDto | null>>>;",
    "type ContextResult = AssertTrue<Equal<ReturnType<EnvironmentCenterFacade['getRequestContext']>, ProjectEnvironmentRequestContextDto>>;",
    "const serviceId: 'workbench.environmentCenter' = ENVIRONMENT_CENTER_SERVICE_ID;",
    'declare const dependencies: EnvironmentCenterDependencies;',
    'const service: EnvironmentCenterService = createEnvironmentCenterService(dependencies);',
    'const disposable: Disposable = service;',
    "const registered: EnvironmentCenterService = (null as unknown as RendererServiceMap)['workbench.environmentCenter'];",
    "const host: Readonly<EnvironmentCenterNativeHostPort> = (null as unknown as RendererServiceMap)['host.environmentCenter'];",
    "const context: ProjectEnvironmentRequestContextDto = { folderName: 'demo', folderKey: 'folder', runtime: 'python:3.11', language: 'python', teamId: '', projectId: '', branch: '', setupCommands: ['pip install -r requirements.txt'] };",
    "const actionRequest: ProjectEnvironmentActionRequestDto = { ...context, environmentAction: 'repair', revision: 'env-1' };",
    "const options: EnvironmentCenterRefreshOptionsDto = { force: true, loading: false };",
    "const snapshot: ProjectEnvironmentSnapshotDto = { schema: 'project-environment/v1', source: 'local', checkedAt: 1, workspace: { kind: 'personal', id: 'folder', name: 'demo' }, language: { id: 'python', source: 'editor' }, runtime: { id: 'python:3.11', status: 'ready' }, manifests: [], packages: { declared: [], installed: [], missing: [], unknown: [] }, dependencyCache: { scope: 'local' }, consistency: { status: 'ready' }, activity: {}, actions: {} };",
    'service.init();',
    "const actionPromise: Promise<void> = service.runAction('refresh');",
    'const refreshPromise: Promise<ProjectEnvironmentSnapshotDto | null> = service.refresh(options);',
    'const currentSnapshot: ProjectEnvironmentSnapshotDto | null = service.getSnapshot();',
    'const currentContext: ProjectEnvironmentRequestContextDto = service.getRequestContext();',
    'const currentlyDisposed: boolean = service.disposed;',
    'service.dispose();',
    '// @ts-expect-error Compatibility consumers cannot observe internal lifecycle state.',
    'const facadeDisposed = (service as EnvironmentCenterFacade).disposed;',
    '// @ts-expect-error Environment action names are a closed set.',
    "service.runAction('clearCache');",
    '// @ts-expect-error Server action payload names are a separate closed set.',
    "const invalidAction: ProjectEnvironmentActionDto = 'refresh';",
    '// @ts-expect-error Setup commands are immutable strings, not opaque values.',
    'context.setupCommands.push(7);',
    '// @ts-expect-error Snapshot DTOs are immutable.',
    "snapshot.source = 'cloud';",
    'declare const platform: RendererPlatform;',
    '// @ts-expect-error Environment Center is private to the trusted workbench.',
    "platform.services.getForPlugin('workbench.environmentCenter');",
    '// @ts-expect-error Native environment authority is private to the trusted workbench.',
    "platform.services.getForPlugin('host.environmentCenter');",
    'void serviceId; void disposable; void registered; void host; void actionRequest;',
    'void actionPromise; void refreshPromise; void currentSnapshot; void currentContext;',
    'void currentlyDisposed; void facadeDisposed; void invalidAction;',
    'void (false as unknown as CoreExportsAreExact);',
    'void (false as unknown as FacadeIsExact);',
    'void (false as unknown as ServiceIsExact);',
    'void (false as unknown as DependenciesAreExact);',
    'void (false as unknown as ServerActionsAreExact);',
    'void (false as unknown as EnvironmentResponseContractIsExact);',
    'void (false as unknown as PlanResponseContractIsExact);',
    'void (false as unknown as ApplyResponseContractIsExact);',
    'void (false as unknown as WireHidesRendererSource);',
    'void (false as unknown as CenterActionsAreExact);',
    'void (false as unknown as ServerActionsPayloadAreExact);',
    'void (false as unknown as ServiceIsDisposable);',
    'void (false as unknown as FacadeHidesDisposed);',
    'void (false as unknown as WorkbenchServiceIsExact);',
    'void (false as unknown as HostServiceIsExact);',
    'void (false as unknown as WorkbenchPluginServiceAbsent);',
    'void (false as unknown as HostPluginServiceAbsent);',
    'void (false as unknown as ServiceIsNotAny);',
    'void (false as unknown as SnapshotIsNotAny);',
    'void (false as unknown as WireHasNoRendererSource);',
    'void (false as unknown as WireCheckedAtIsExact);',
    'void (false as unknown as EnvironmentResponseIsExact);',
    'void (false as unknown as PlanResponseIsExact);',
    'void (false as unknown as ApplyResponseIsExact);',
    'void (false as unknown as RefreshResult);',
    'void (false as unknown as ContextResult);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__environment-center-types-contract.ts',
    source
  });
});
