'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('extension host contracts keep broker data untrusted and runtime registries dynamic', () => {
  const source = [
    "import { PluginExtensionHost } from '../renderer/core/plugin-extension-host';",
    "import { PluginPermission } from '../renderer/core/plugin-runtime';",
    "import type { Disposable } from '../types/lifecycle';",
    'import type {',
    '  PluginExtensionChangeEventDto,',
    '  PluginExtensionDescriptorDto,',
    '  PluginExtensionDescriptorRegistrationDto,',
    '  PluginExtensionErrorEvent,',
    '  PluginExtensionErrorSource,',
    '  PluginExtensionHostCommandRegistryPort,',
    '  PluginExtensionHostConstructor,',
    '  PluginExtensionHostContract,',
    '  PluginExtensionHostContributionRegistryPort,',
    '  PluginExtensionHostOptions,',
    '  PluginExtensionHostServiceRegistryPort,',
    '  PluginExtensionLifecycleStatusDto,',
    '  PluginExtensionLocaleDto,',
    '  PluginExtensionLocalizationDto,',
    '  PluginExtensionObservedErrorEvent,',
    '  PluginExtensionOperationResultDto,',
    '  PluginExtensionRefreshCompletedDto,',
    '  PluginExtensionRefreshFailureDto,',
    '  PluginExtensionRefreshRejectedDto,',
    '  PluginExtensionRefreshResultDto,',
    '  PluginExtensionSnapshotDto,',
    '  PluginExtensionStatusDto',
    "} from '../types/renderer-platform';",
    'type Equal<Left, Right> = (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2)',
    '    ? (<Value>() => Value extends Right ? 1 : 2) extends',
    '      (<Value>() => Value extends Left ? 1 : 2) ? true : false',
    '    : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    'type AssertFalse<Value extends false> = Value;',
    'type IsUnknown<Value> = IsAny<Value> extends true',
    '  ? false',
    '  : unknown extends Value ? ([keyof Value] extends [never] ? true : false) : false;',
    'interface TestPluginServices {',
    "  readonly 'workbench.test': Readonly<{ snapshot(): readonly string[] }>;",
    '}',
    'const inertDisposable: Disposable = { dispose() {} };',
    'const testService: TestPluginServices[\'workbench.test\'] = Object.freeze({',
    "  snapshot: () => Object.freeze(['ready'])",
    '});',
    'const services: PluginExtensionHostServiceRegistryPort<TestPluginServices> = {',
    '  getForPluginDynamic<Id extends string>(',
    '    id: Id',
    '  ): Id extends keyof TestPluginServices ? TestPluginServices[Id] : unknown {',
    '    return (id === \'workbench.test\' ? testService : undefined) as',
    '      Id extends keyof TestPluginServices ? TestPluginServices[Id] : unknown;',
    '  }',
    '};',
    'const commands: PluginExtensionHostCommandRegistryPort = {',
    '  registerDynamic(_id, _handler, _metadata) { return inertDisposable; },',
    '  async executeDynamic(_id, ..._args) { return undefined; },',
    '  async executeDynamicIsolated(_id, ..._args) {',
    '    return { ok: true as const, value: undefined };',
    '  },',
    '  disposeOwner(_owner) {}',
    '};',
    'const contributions: PluginExtensionHostContributionRegistryPort = {',
    '  registerDynamic(_point, _contribution, _options) { return inertDisposable; },',
    '  disposeOwner(_owner) {}',
    '};',
    "const knownService = services.getForPluginDynamic('workbench.test');",
    'const knownSnapshot: readonly string[] = knownService.snapshot();',
    "const unknownService = services.getForPluginDynamic('future.service');",
    'type UnknownServiceStaysUnknown = AssertTrue<IsUnknown<typeof unknownService>>;',
    '// @ts-expect-error Extension host service ports expose only dynamic lookup.',
    "services.getForPlugin('workbench.test');",
    '// @ts-expect-error Extension host command ports expose only dynamic registration.',
    "commands.register('acme.typed.command', () => undefined);",
    '// @ts-expect-error Extension host command ports expose only dynamic execution.',
    "commands.execute('acme.typed.command');",
    '// @ts-expect-error Extension host contribution ports expose only dynamic registration.',
    "contributions.register('tasks', { id: 'acme.typed.tasks' });",
    'const descriptor: PluginExtensionDescriptorRegistrationDto = {',
    "  id: 'acme.typed',",
    "  manifest: { id: 'acme.typed', version: '1.0.0', engines: { pluginApi: '^1.6.0' },",
    '    permissions: [PluginPermission.COMMANDS_REGISTER] },',
    '  grantedPermissions: [PluginPermission.COMMANDS_REGISTER],',
    "  revision: 'revision-1'",
    '};',
    'const normalizedDescriptor: PluginExtensionDescriptorDto = {',
    "  id: 'acme.typed',",
    '  manifest: {',
    "    id: 'acme.typed', version: '1.0.0', displayName: 'Typed extension',",
    "    engines: { pluginApi: '^1.6.0' },",
    '    permissions: [PluginPermission.COMMANDS_REGISTER], contributes: {}',
    '  },',
    '  grantedPermissions: [PluginPermission.COMMANDS_REGISTER],',
    "  revision: 'revision-1'",
    '};',
    '// @ts-expect-error An extension descriptor always carries a manifest.',
    "const missingManifest: PluginExtensionDescriptorRegistrationDto = { id: 'acme.missing' };",
    '// @ts-expect-error Granted permissions are a closed host contract.',
    "const invalidPermission: PluginExtensionDescriptorRegistrationDto = { ...descriptor, grantedPermissions: ['future.permission'] };",
    '// @ts-expect-error Descriptor revisions are strings.',
    'const invalidRevision: PluginExtensionDescriptorRegistrationDto = { ...descriptor, revision: 1 };',
    "const locale: PluginExtensionLocaleDto = 'ja';",
    "const localization: PluginExtensionLocalizationDto = { locale, messages: { title: 'Title' } };",
    "const status: PluginExtensionStatusDto = 'active';",
    "const lifecycleStatus: PluginExtensionLifecycleStatusDto = 'stopped';",
    'const snapshot: PluginExtensionSnapshotDto = {',
    "  id: descriptor.id, version: descriptor.manifest.version, displayName: 'Typed extension',",
    '  status, grantedPermissions: [PluginPermission.COMMANDS_REGISTER]',
    '};',
    'const change: PluginExtensionChangeEventDto = {',
    "  id: descriptor.id, status: lifecycleStatus, version: '1.0.0'",
    '};',
    '// @ts-expect-error Extension lifecycle events use a closed status set.',
    "const invalidChange: PluginExtensionChangeEventDto = { id: descriptor.id, status: 'paused', version: '1.0.0' };",
    '// @ts-expect-error Extension snapshots are immutable.',
    "snapshot.status = 'deactivating';",
    'const refreshFailure: PluginExtensionRefreshFailureDto = { id: descriptor.id, error: new Error(\'failed\') };',
    'const completedRefresh: PluginExtensionRefreshCompletedDto = {',
    '  ok: false, activated: [], deactivated: [], failures: [refreshFailure]',
    '};',
    "const rejectedRefresh: PluginExtensionRefreshRejectedDto = { ok: false, error: new Error('unavailable') };",
    'const refreshResult: PluginExtensionRefreshResultDto =',
    '  Math.random() > 0.5 ? completedRefresh : rejectedRefresh;',
    '// @ts-expect-error A rejected refresh cannot also expose completed result arrays.',
    'const ambiguousRefresh: PluginExtensionRefreshRejectedDto = { ok: false, error: null, activated: [] };',
    "const errorSource: PluginExtensionErrorSource = 'extension-protocol';",
    'const errorEvent: PluginExtensionErrorEvent = { source: errorSource, id: descriptor.id, error: new Error(\'bad message\') };',
    "const unattributedError: PluginExtensionErrorEvent = { source: 'extension-refresh', id: '', error: new Error('unavailable') };",
    'const observedError: PluginExtensionObservedErrorEvent = errorEvent;',
    '// @ts-expect-error Extension error sources are closed and attributable.',
    "const invalidError: PluginExtensionErrorEvent = { source: 'future-source', id: descriptor.id, error: null };",
    'const options: PluginExtensionHostOptions<TestPluginServices> = {',
    '  services, commands, contributions,',
    "  listDescriptors: async () => [descriptor],",
    "  loadEntry: async (id) => ({ id, source: 'export function activate() {}' }),",
    '  loadLocalization: async (_id, requestedLocale) => ({ locale: requestedLocale, messages: {} }),',
    '  broker: async (_id, _method, _args) => ({ authorized: true }),',
    '  sandboxFactory: () => ({',
    '    ready: Promise.resolve(), postMessage(_message) {}, dispose() {}',
    '  }),',
    '  getLocale: () => locale,',
    '  onLocaleChange: (_listener) => inertDisposable,',
    '  getCommandPalette: () => ({',
    '    supportsDisposables: true,',
    '    register: () => inertDisposable',
    '  }),',
    '  serviceSnapshots: {',
    '    \'workbench.test\': (_id, service) => { const remainsUnknown: unknown = service; return remainsUnknown; }',
    '  },',
    '  localize: (key) => key,',
    '  onError(event) { const remainsUnknown: unknown = event.error; void remainsUnknown; },',
    '  activationTimeoutMs: 100, invocationTimeoutMs: 100, deactivationTimeoutMs: 100',
    '};',
    '// @ts-expect-error The entry loader is mandatory at the host boundary.',
    'const missingLoader: PluginExtensionHostOptions<TestPluginServices> = { services, commands, contributions };',
    'const host = new PluginExtensionHost<TestPluginServices>(options);',
    'const hostContract: PluginExtensionHostContract = host;',
    'const hostConstructor: PluginExtensionHostConstructor = PluginExtensionHost;',
    'const activation: Promise<PluginExtensionOperationResultDto> = hostContract.activate(descriptor);',
    'const deactivation: Promise<PluginExtensionOperationResultDto> = hostContract.deactivate(descriptor.id);',
    'const refresh: Promise<PluginExtensionRefreshResultDto> = hostContract.refresh([descriptor]);',
    'const startup: Promise<PluginExtensionRefreshResultDto> = hostContract.start();',
    'const snapshots: readonly PluginExtensionSnapshotDto[] = hostContract.list();',
    'const changeSubscription: Disposable = hostContract.onDidChange((event) => {',
    '  const typedEvent: PluginExtensionChangeEventDto = event;',
    '  void typedEvent;',
    '});',
    'const handled: boolean = hostContract.handleAgentModelEvent({ pluginId: descriptor.id });',
    'const disposal: Promise<void> = hostContract.dispose();',
    'type HostIsNotAny = AssertFalse<IsAny<typeof host>>;',
    'type DescriptorMatches = AssertTrue<Equal<typeof normalizedDescriptor.id, string>>;',
    'void knownSnapshot; void unknownService; void descriptor; void normalizedDescriptor; void missingManifest;',
    'void invalidPermission; void invalidRevision; void localization; void snapshot; void change; void invalidChange;',
    'void refreshResult; void ambiguousRefresh; void unattributedError; void observedError; void invalidError; void options; void missingLoader;',
    'void host; void hostContract; void hostConstructor; void activation; void deactivation; void refresh; void startup;',
    'void snapshots; void changeSubscription; void handled; void disposal;',
    'void (null as unknown as UnknownServiceStaysUnknown);',
    'void (null as unknown as HostIsNotAny);',
    'void (null as unknown as DescriptorMatches);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__plugin-extension-host-types-contract.ts',
    source
  });
});
