'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('plugin runtime contracts keep trusted modules typed and runtime ids explicit', () => {
  const source = [
    "import { PLUGIN_API_VERSION, PluginPermission, PluginRuntime, validatePluginManifest } from '../renderer/core/plugin-runtime';",
    "import type { Disposable } from '../types/lifecycle';",
    "import type { RendererPlatform, RendererPluginServiceMap } from '../types/renderer-platform';",
    'import type {',
    '  PluginApiVersionDto,',
    '  PluginManifestRegistrationDto,',
    '  PluginPermissionDto,',
    '  PluginRuntimeAgentProvider,',
    '  PluginRuntimeContext,',
    '  PluginRuntimeContract,',
    '  PluginRuntimeModule,',
    '  PluginRuntimeOptions,',
    '  PluginRuntimeOperationResultDto,',
    '  PluginRuntimeSourceControlProvider',
    "} from '../types/plugin-runtime';",
    'type Equal<Left, Right> = (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2)',
    '    ? (<Value>() => Value extends Right ? 1 : 2) extends',
    '      (<Value>() => Value extends Left ? 1 : 2) ? true : false',
    '    : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    'type IsUnknown<Value> = IsAny<Value> extends true',
    '  ? false',
    '  : unknown extends Value ? ([keyof Value] extends [never] ? true : false) : false;',
    'type ValueOf<Value> = Value[keyof Value];',
    'const apiVersion: PluginApiVersionDto = PLUGIN_API_VERSION;',
    'const permission: PluginPermissionDto = PluginPermission.AGENTS_REGISTER;',
    'type PermissionConstantsMatch = AssertTrue<Equal<ValueOf<typeof PluginPermission>, PluginPermissionDto>>;',
    'const registration: PluginManifestRegistrationDto = {',
    "  id: 'acme.typed', version: '1.0.0', engines: { pluginApi: '^1.0.0' },",
    '  permissions: [PluginPermission.COMMANDS_REGISTER]',
    '};',
    'const manifest = validatePluginManifest(registration);',
    'const normalizedApiRange: string = manifest.engines.pluginApi;',
    '// @ts-expect-error Normalized manifest permissions are immutable.',
    'manifest.permissions.push(PluginPermission.SERVICES_READ);',
    '// @ts-expect-error Permission names are a closed contract.',
    "const badRegistration: PluginManifestRegistrationDto = { ...registration, permissions: ['future.permission'] };",
    'declare const context: PluginRuntimeContext<RendererPluginServiceMap>;',
    "const icon = context.services.get('workbench.fileIcons').getFileIcon('main.ts');",
    "const unknownService = context.services.get('future.service');",
    'type UnknownServiceStaysUnknown = AssertTrue<IsUnknown<typeof unknownService>>;',
    "const commandRegistration: Disposable = context.commands.register('acme.typed.command', () => 1);",
    "const contributionRegistration: Disposable = context.contributions.register('tasks', { id: 'acme.typed.tasks' });",
    "const optionIdentifiedContribution = context.contributions.register('tasks', { label: 'Tasks' }, { id: 'acme.typed.option-tasks' });",
    '// @ts-expect-error A contribution id is required either on the data or in registration options.',
    "context.contributions.register('tasks', { label: 'Missing id' });",
    "interface NamedContribution { readonly id: string; readonly label: string }",
    "declare const namedContribution: NamedContribution;",
    "const namedRegistration = context.contributions.register('tasks', namedContribution);",
    '// @ts-expect-error Contributions must be data objects rather than callable objects.',
    "context.contributions.register('tasks', Object.assign(() => undefined, { id: 'acme.typed.callable' }));",
    "class ConstructableContribution { readonly id = 'acme.typed.constructable'; }",
    '// @ts-expect-error Contribution constructors are executable values rather than data objects.',
    "context.contributions.register('tasks', ConstructableContribution);",
    "declare const unionContribution: { readonly id: string } | ((() => void) & { readonly id: string });",
    '// @ts-expect-error A union containing an executable value is not a data contribution.',
    "context.contributions.register<typeof unionContribution>('tasks', unionContribution);",
    '// @ts-expect-error Agent registration uses the dedicated context port.',
    "context.contributions.register('agents', { id: 'acme.typed.agent' });",
    'declare const sourceControlProvider: PluginRuntimeSourceControlProvider;',
    "const sourceState = sourceControlProvider.setState({ phase: 'ready', title: 'Repository' });",
    'declare const agentProvider: PluginRuntimeAgentProvider;',
    "const agentVersion = agentProvider.clearState();",
    '// @ts-expect-error The trusted legacy runtime does not expose Worker state patching.',
    "agentProvider.updateState({ expectedVersion: 0, operations: [] });",
    'const pluginModule: PluginRuntimeModule<RendererPluginServiceMap> = {',
    '  activate(pluginContext) {',
    "    pluginContext.services.get('workbench.projectTasks').list();",
    '    // @ts-expect-error Plugin service views do not expose host mutation methods.',
    "    pluginContext.services.get('workbench.projectTasks').refresh();",
    '    pluginContext.subscriptions.add({ async dispose() {} });',
    '    return { async dispose() {} };',
    '  },',
    '  async deactivate() {}',
    '};',
    'declare const concrete: PluginRuntime<RendererPluginServiceMap>;',
    'declare const options: PluginRuntimeOptions<RendererPluginServiceMap>;',
    'declare const dynamicOnlyServices: { getForPluginDynamic(id: string): unknown; disposeOwner(owner: string): void };',
    '// @ts-expect-error The declared plugin service map must be backed by a matching typed registry port.',
    'new PluginRuntime<RendererPluginServiceMap>({ ...options, services: dynamicOnlyServices });',
    'const runtime: PluginRuntimeContract<RendererPluginServiceMap> = concrete;',
    'const activation: Promise<PluginRuntimeOperationResultDto> = runtime.activate(registration, pluginModule);',
    'declare const result: PluginRuntimeOperationResultDto;',
    "if (result.ok) { const id: string = result.id; void id; } else { const error: unknown = result.error; void error; }",
    'declare const platform: RendererPlatform;',
    'type PlatformUsesRuntimeContract = AssertTrue<Equal<',
    "  RendererPlatform['plugins'], PluginRuntimeContract<RendererPluginServiceMap>",
    '>>;',
    "const dynamicService = platform.services.getForPluginDynamic('future.service');",
    'type DynamicServiceStaysUnknown = AssertTrue<IsUnknown<typeof dynamicService>>;',
    '// @ts-expect-error The strict plugin service lookup only accepts the closed service map.',
    "platform.services.getForPlugin('future.service');",
    "const dynamicCommand = platform.commands.registerDynamic('acme.dynamic.command', () => undefined);",
    "const dynamicContribution = platform.contributions.registerDynamic('future.point', { id: 'acme.dynamic.point' });",
    'void apiVersion; void permission; void registration; void manifest; void normalizedApiRange; void badRegistration;',
    'void icon; void unknownService; void commandRegistration; void contributionRegistration; void optionIdentifiedContribution;',
    'void namedRegistration;',
    'void sourceState; void agentVersion; void runtime; void activation; void result; void platform;',
    'void dynamicService; void dynamicCommand; void dynamicContribution;',
    'void (null as unknown as PermissionConstantsMatch);',
    'void (null as unknown as UnknownServiceStaysUnknown);',
    'void (null as unknown as DynamicServiceStaysUnknown);',
    'void (null as unknown as PlatformUsesRuntimeContract);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__plugin-runtime-types-contract.ts',
    source
  });
});
