'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('extension protocol contracts keep wire envelopes narrow and payloads untrusted', () => {
  const source = [
    'import {',
    '  EXTENSION_PROTOCOL_VERSION,',
    '  PLUGIN_RPC_RESULT_MARKER,',
    '  PLUGIN_RPC_RESULT_VERSION,',
    '  ExtensionErrorCode,',
    '  ExtensionHostMethod,',
    '  ExtensionMessageType,',
    '  ExtensionSandboxMethod,',
    '  assertExtensionOwnedId,',
    '  cloneExtensionData,',
    '  createExtensionDataCloner,',
    '  createExtensionError,',
    '  deserializeExtensionError,',
    '  isExtensionMessage,',
    '  isExtensionRequestId,',
    '  isNamespacedExtensionId,',
    '  isPlainObject,',
    '  isSerializedExtensionError,',
    '  serializeExtensionError,',
    '  unwrapPluginRpcResult',
    "} from '../renderer/core/plugin-extension-protocol';",
    'import type {',
    '  ExtensionActivatedMessageDto,',
    '  ExtensionData,',
    '  ExtensionDataCloneOptions,',
    '  ExtensionDataCloner,',
    '  ExtensionErrorCodeDto,',
    '  ExtensionFailureResponseMessageDto,',
    '  ExtensionHostMethodDto,',
    '  ExtensionInboundMessageDto,',
    '  ExtensionMessageTypeDto,',
    '  ExtensionProtocolError,',
    '  ExtensionRequestMessageDto,',
    '  ExtensionResponseMessageDto,',
    '  ExtensionSandboxMethodDto,',
    '  ExtensionSuccessResponseMessageDto,',
    '  PluginRpcResultDto,',
    '  SerializedExtensionErrorDto',
    "} from '../types/plugin-extension-protocol';",
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    'type AssertFalse<Value extends false> = Value;',
    'type AssertTrue<Value extends true> = Value;',
    'type Equal<Left, Right> = (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2)',
    '    ? (<Value>() => Value extends Right ? 1 : 2) extends',
    '      (<Value>() => Value extends Left ? 1 : 2) ? true : false',
    '    : false;',
    'type ValueOf<Value> = Value[keyof Value];',
    'type IsUnknown<Value> = IsAny<Value> extends true',
    '  ? false',
    '  : unknown extends Value',
    '    ? keyof Value extends never ? true : false',
    '    : false;',
    'const protocolVersion: 1 = EXTENSION_PROTOCOL_VERSION;',
    "const resultMarker: '__bobocloudPluginRpcResult' = PLUGIN_RPC_RESULT_MARKER;",
    'const resultVersion: 1 = PLUGIN_RPC_RESULT_VERSION;',
    'const messageType: ExtensionMessageTypeDto = ExtensionMessageType.REQUEST;',
    'const hostMethod: ExtensionHostMethodDto = ExtensionHostMethod.AGENT_BROKER_REQUEST;',
    'const sandboxMethod: ExtensionSandboxMethodDto = ExtensionSandboxMethod.AGENT_MODEL_EVENT;',
    'const errorCode: ExtensionErrorCodeDto = ExtensionErrorCode.PROTOCOL;',
    '// @ts-expect-error Frozen message constants are readonly literals.',
    "ExtensionMessageType.REQUEST = 'other';",
    '// @ts-expect-error Host methods are a closed constant set.',
    "const invalidHostMethod: ExtensionHostMethodDto = 'future.method';",
    'const request: ExtensionRequestMessageDto = {',
    "  protocolVersion: 1, type: 'request', id: 'worker_1', method: 'future.method', args: { value: 1 }",
    '};',
    'const success: ExtensionSuccessResponseMessageDto = {',
    "  protocolVersion: 1, type: 'response', id: 1, ok: true, value: { accepted: true }",
    '};',
    'const failure: ExtensionFailureResponseMessageDto = {',
    "  protocolVersion: 1, type: 'response', id: 2, ok: false, error: { code: 'SCM_GIT_NO_WORKSPACE', message: 'Open a workspace.' }",
    '};',
    'const activated: ExtensionActivatedMessageDto = { protocolVersion: 1, type: \'activated\' };',
    'const response: ExtensionResponseMessageDto = Math.random() > 0.5 ? success : failure;',
    'const inbound: ExtensionInboundMessageDto = request;',
    'const rpcResult: PluginRpcResultDto = {',
    "  __bobocloudPluginRpcResult: 1, ok: false, error: { code: 'DOMAIN_ERROR', message: 'Failed.' }",
    '};',
    '// @ts-expect-error The protocol version is fixed at one.',
    "const wrongVersion: ExtensionRequestMessageDto = { protocolVersion: 2, type: 'request', id: 1, method: 'x', args: null };",
    "const mixedResponse = { protocolVersion: 1 as const, type: 'response' as const, id: 1, ok: true as const, value: null, error: { code: 'BAD', message: 'bad' } };",
    '// @ts-expect-error A successful response cannot carry a failure envelope, including through a non-fresh object.',
    'const ambiguousResponse: ExtensionResponseMessageDto = mixedResponse;',
    "const mixedRpcResult = { __bobocloudPluginRpcResult: 1 as const, ok: false as const, error: { code: 'BAD', message: 'bad' }, value: null };",
    '// @ts-expect-error A failed RPC result cannot also carry a success value.',
    'const ambiguousRpcResult: PluginRpcResultDto = mixedRpcResult;',
    'declare const candidate: unknown;',
    'if (isExtensionMessage(candidate)) {',
    '  const narrowed: ExtensionInboundMessageDto = candidate;',
    "  if (candidate.type === 'request') {",
    '    const methodRemainsUntrusted: string = candidate.method;',
    '    const argsRemainUnknown: unknown = candidate.args;',
    '    // @ts-expect-error Envelope validation does not validate request payload fields.',
    '    candidate.args.value;',
    '    // @ts-expect-error Envelope validation does not authorize the requested method.',
    '    const authorizedMethod: ExtensionHostMethodDto = candidate.method;',
    '    void methodRemainsUntrusted; void argsRemainUnknown; void authorizedMethod;',
    '  }',
    "  if (candidate.type === 'response') {",
    '    if (candidate.ok) {',
    '      const valueRemainsUnknown: unknown = candidate.value;',
    '      const absentError: undefined = candidate.error;',
    '      void valueRemainsUnknown; void absentError;',
    '    } else {',
    '      const serializedFailure: SerializedExtensionErrorDto = candidate.error;',
    '      const absentValue: undefined = candidate.value;',
    '      void serializedFailure; void absentValue;',
    '    }',
    '  }',
    '  void narrowed;',
    '}',
    'if (isSerializedExtensionError(candidate)) {',
    '  const serializedCandidate: SerializedExtensionErrorDto = candidate;',
    '  void serializedCandidate;',
    '}',
    'if (isExtensionRequestId(candidate)) { const requestId: number | string = candidate; void requestId; }',
    'if (isNamespacedExtensionId(candidate)) { const extensionId: string = candidate; void extensionId; }',
    'if (isPlainObject(candidate)) { const field: unknown = candidate.field; void field; }',
    "const domainError: ExtensionProtocolError = createExtensionError('SCM_GIT_NO_WORKSPACE', 'Open a workspace.');",
    "const restored: ExtensionProtocolError = deserializeExtensionError({ code: 'DOMAIN_ERROR', message: 'Failed.' });",
    'const serialized: Readonly<SerializedExtensionErrorDto> = serializeExtensionError(domainError);',
    '// @ts-expect-error Serialized errors are immutable DTOs.',
    "serialized.code = 'OTHER';",
    "const ownedId: string = assertExtensionOwnedId('acme.plugin', 'acme.plugin.command', 'Command');",
    'const cloneOptions: ExtensionDataCloneOptions = { maxDepth: 8, maxItems: 64, maxStringLength: 1024, maxBytes: 4096 };',
    'const cloner: ExtensionDataCloner = createExtensionDataCloner();',
    'const cloned: ExtensionData = cloner({ nested: [true, 1, undefined] }, cloneOptions);',
    'const directClone: ExtensionData = cloneExtensionData({ ok: true });',
    '// @ts-expect-error Clone limits must be numeric.',
    "cloneExtensionData(null, { maxDepth: '8' });",
    'type RequestArgsAreUnknown = AssertTrue<IsUnknown<ExtensionRequestMessageDto[\'args\']>>;',
    'type SuccessValueIsUnknown = AssertTrue<IsUnknown<ExtensionSuccessResponseMessageDto[\'value\']>>;',
    'type UnwrappedValueIsUnknown = AssertTrue<IsUnknown<ReturnType<typeof unwrapPluginRpcResult>>>;',
    'type GuardIsNotAny = AssertFalse<IsAny<ExtensionInboundMessageDto>>;',
    'type CloneIsNotAny = AssertFalse<IsAny<ReturnType<typeof cloneExtensionData>>>;',
    'type MessageConstantsMatch = AssertTrue<Equal<ValueOf<typeof ExtensionMessageType>, ExtensionMessageTypeDto>>;',
    'type HostMethodConstantsMatch = AssertTrue<Equal<ValueOf<typeof ExtensionHostMethod>, ExtensionHostMethodDto>>;',
    'type SandboxMethodConstantsMatch = AssertTrue<Equal<ValueOf<typeof ExtensionSandboxMethod>, ExtensionSandboxMethodDto>>;',
    'type ErrorCodeConstantsMatch = AssertTrue<Equal<ValueOf<typeof ExtensionErrorCode>, ExtensionErrorCodeDto>>;',
    'void protocolVersion; void resultMarker; void resultVersion; void messageType; void hostMethod;',
    'void sandboxMethod; void errorCode; void invalidHostMethod; void request; void success; void failure;',
    'void activated; void response; void inbound; void rpcResult; void wrongVersion; void mixedResponse;',
    'void ambiguousResponse; void mixedRpcResult; void ambiguousRpcResult;',
    'void restored; void serialized; void ownedId; void cloned; void directClone;',
    'void (null as unknown as RequestArgsAreUnknown);',
    'void (null as unknown as SuccessValueIsUnknown);',
    'void (null as unknown as UnwrappedValueIsUnknown);',
    'void (null as unknown as GuardIsNotAny);',
    'void (null as unknown as CloneIsNotAny);',
    'void (null as unknown as MessageConstantsMatch);',
    'void (null as unknown as HostMethodConstantsMatch);',
    'void (null as unknown as SandboxMethodConstantsMatch);',
    'void (null as unknown as ErrorCodeConstantsMatch);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__plugin-extension-protocol-types-contract.ts',
    source
  });
});
