'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('plugin management contracts preserve typed DTOs, disposables, and host-only services', () => {
  const source = [
    "import type { Disposable } from '../types/lifecycle';",
    'import type {',
    '  PluginDetailsDto,',
    '  PluginDetailsService,',
    '  PluginManagementChangedDto,',
    '  PluginManagementHost,',
    '  PluginManagerUIService,',
    '  PluginMarketplaceSnapshotDto,',
    '  PluginOpenFolderResultDto,',
    '  PluginPermissionDto,',
    '  PluginStatusDto,',
    '  PluginUninstallResultDto,',
    '  RendererPlatform,',
    '  RendererPluginServiceMap,',
    '  RendererServiceMap',
    "} from '../types/renderer-platform';",
    'type Equal<Left, Right> =',
    '  (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2) ? true : false;',
    'type Expect<Value extends true> = Value;',
    "type ListResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['list']>>, readonly PluginStatusDto[]>>;",
    "type GetResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['get']>>, PluginStatusDto | null>>;",
    "type InstallResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['install']>>, PluginStatusDto | null>>;",
    "type EnableResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['enable']>>, PluginStatusDto>>;",
    "type DisableResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['disable']>>, PluginStatusDto>>;",
    "type GrantResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['grant']>>, PluginStatusDto>>;",
    "type RevokeResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['revoke']>>, PluginStatusDto>>;",
    "type RefreshResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['refresh']>>, readonly PluginStatusDto[]>>;",
    "type UninstallResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['uninstall']>>, PluginUninstallResultDto>>;",
    "type OpenFolderResult = Expect<Equal<Awaited<ReturnType<PluginManagementHost['openFolder']>>, PluginOpenFolderResultDto>>;",
    "type ChangeSubscription = Expect<Equal<ReturnType<PluginManagementHost['onDidChange']>, Disposable>>;",
    "type OpenSubscription = Expect<Equal<ReturnType<PluginManagementHost['onOpenManager']>, Disposable>>;",
    "type HostRequestedPermissions = Expect<Equal<PluginStatusDto['requestedPermissions'], readonly PluginPermissionDto[]>>;",
    "type HostGrantedPermissions = Expect<Equal<PluginStatusDto['grantedPermissions'], readonly PluginPermissionDto[]>>;",
    "type DetailsRequestedPermissions = Expect<Equal<PluginDetailsDto['requestedPermissions'], readonly string[]>>;",
    "type DetailsGrantedPermissions = Expect<Equal<PluginDetailsDto['grantedPermissions'], readonly string[]>>;",
    'declare const host: PluginManagementHost;',
    'const changeSubscription: Disposable = host.onDidChange((change: PluginManagementChangedDto) => {',
    '  const snapshot: readonly PluginStatusDto[] = change.plugins;',
    '  void snapshot; void change.reason;',
    '});',
    'const openSubscription: Disposable = host.onOpenManager(() => {});',
    'const marketplace = host.marketplace;',
    'if (marketplace) {',
    '  const listed: Promise<PluginMarketplaceSnapshotDto> = marketplace.list();',
    '  const refreshed: Promise<PluginMarketplaceSnapshotDto> = marketplace.refresh();',
    '  const installed: Promise<PluginStatusDto> = marketplace.install(\'acme.plugin\');',
    '  void listed; void refreshed; void installed;',
    '}',
    'declare const platform: RendererPlatform;',
    "const management: RendererServiceMap['host.pluginManagement'] = platform.services.require('host.pluginManagement');",
    "const managerUI: RendererServiceMap['workbench.pluginManagerUI'] = platform.services.require('workbench.pluginManagerUI');",
    "const details: RendererServiceMap['workbench.pluginDetails'] = platform.services.require('workbench.pluginDetails');",
    "type ManagementHostOnly = 'host.pluginManagement' extends keyof RendererPluginServiceMap ? true : false;",
    "type ManagerUIHostOnly = 'workbench.pluginManagerUI' extends keyof RendererPluginServiceMap ? true : false;",
    "type DetailsHostOnly = 'workbench.pluginDetails' extends keyof RendererPluginServiceMap ? true : false;",
    'const managementHostOnly: ManagementHostOnly = false;',
    'const managerUIHostOnly: ManagerUIHostOnly = false;',
    'const detailsHostOnly: DetailsHostOnly = false;',
    '// @ts-expect-error Plugin management is a private native-host capability.',
    "platform.services.getForPlugin('host.pluginManagement');",
    '// @ts-expect-error The plugin manager UI is a host-owned workbench surface.',
    "platform.services.getForPlugin('workbench.pluginManagerUI');",
    '// @ts-expect-error Plugin details are a host-owned workbench surface.',
    "platform.services.getForPlugin('workbench.pluginDetails');",
    'declare const status: PluginStatusDto;',
    '// @ts-expect-error Plugin status DTOs are immutable.',
    'status.enabled = false;',
    'changeSubscription.dispose(); openSubscription.dispose();',
    'const typedManagerUI: PluginManagerUIService = managerUI;',
    'const typedDetails: PluginDetailsService = details;',
    'void management; void typedManagerUI; void typedDetails;',
    'void managementHostOnly; void managerUIHostOnly; void detailsHostOnly;',
    'void (0 as unknown as ListResult); void (0 as unknown as GetResult);',
    'void (0 as unknown as InstallResult); void (0 as unknown as EnableResult);',
    'void (0 as unknown as DisableResult); void (0 as unknown as GrantResult);',
    'void (0 as unknown as RevokeResult); void (0 as unknown as RefreshResult);',
    'void (0 as unknown as UninstallResult); void (0 as unknown as OpenFolderResult);',
    'void (0 as unknown as ChangeSubscription); void (0 as unknown as OpenSubscription);',
    'void (0 as unknown as HostRequestedPermissions); void (0 as unknown as HostGrantedPermissions);',
    'void (0 as unknown as DetailsRequestedPermissions); void (0 as unknown as DetailsGrantedPermissions);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__plugin-management-types-contract.ts',
    source
  });
});
