'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('source-control DTOs preserve normalized defaults, discriminants, and store ownership', () => {
  const source = [
    "import type { Disposable } from '../types/lifecycle';",
    'import type { SourceControlDescriptorDto, SourceControlDescriptorRegistrationDto } from \'../types/contributions\';',
    'import type {',
    '  SourceControlAddedEvent,',
    '  SourceControlActionDto,',
    '  SourceControlActionRegistrationDto,',
    '  SourceControlButtonActionDto,',
    '  SourceControlButtonActionRegistrationDto,',
    '  SourceControlCheckboxFormFieldDto,',
    '  SourceControlCheckboxFormFieldRegistrationDto,',
    '  SourceControlChangeEvent,',
    '  SourceControlClearedEvent,',
    '  SourceControlCommandDetailsDto,',
    '  SourceControlCommandPayloadDto,',
    '  SourceControlFormDto,',
    '  SourceControlFormFieldDto,',
    '  SourceControlFormFieldRegistrationDto,',
    '  SourceControlFormRegistrationDto,',
    '  SourceControlFormValues,',
    '  SourceControlMenuActionDto,',
    '  SourceControlMenuActionRegistrationDto,',
    '  SourceControlRawFormValues,',
    '  SourceControlRegistrationOptions,',
    '  SourceControlRemovedEvent,',
    '  SourceControlSectionDto,',
    '  SourceControlSectionRegistrationDto,',
    '  SourceControlSelectFormFieldDto,',
    '  SourceControlSelectFormFieldRegistrationDto,',
    '  SourceControlSnapshot,',
    '  SourceControlStateDto,',
    '  SourceControlStateChangedEvent,',
    '  SourceControlStateHandle,',
    '  SourceControlStateRegistrationDto,',
    '  SourceControlStateStoreContract,',
    '  SourceControlStateStoreErrorEvent,',
    '  SourceControlStateStoreOptions,',
    '  SourceControlSummaryDto,',
    '  SourceControlSummaryRegistrationDto,',
    '  SourceControlTextFormFieldDto,',
    '  SourceControlTextFormFieldRegistrationDto,',
    '  SourceControlTextareaFormFieldDto,',
    '  SourceControlTextareaFormFieldRegistrationDto,',
    '  SourceControlToolbarActionDto,',
    '  SourceControlToolbarActionRegistrationDto,',
    '  SourceControlVersionDto',
    "} from '../types/renderer-platform';",
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    'type AssertFalse<Value extends false> = Value;',
    "const descriptorInput: SourceControlDescriptorRegistrationDto = { id: 'acme.scm', title: 'SCM' };",
    'const descriptor: SourceControlDescriptorDto = {',
    "  id: 'acme.scm', title: 'SCM', icon: 'git-branch', order: 0, openCommand: null",
    '};',
    'const descriptorWithNullableCommand: SourceControlDescriptorRegistrationDto = {',
    "  id: 'acme.scm', title: 'SCM', openCommand: null",
    '};',
    '// @ts-expect-error A normalized descriptor always has its defaulted icon.',
    "const missingIcon: SourceControlDescriptorDto = { id: 'acme.scm', title: 'SCM', order: 0, openCommand: null };",
    '// @ts-expect-error Normalized nullable fields use null, not undefined.',
    "const undefinedOpenCommand: SourceControlDescriptorDto = { id: 'acme.scm', title: 'SCM', icon: 'git-branch', order: 0, openCommand: undefined };",
    'const summaryInput: SourceControlSummaryRegistrationDto = {',
    "  title: null, items: [{ label: 'Branch', value: 'main', detail: null }]",
    '};',
    'declare const summary: SourceControlSummaryDto;',
    'const summaryTitle: string | null = summary.title;',
    'const summaryDetail: string | null = summary.items[0]!.detail;',
    '// @ts-expect-error A normalized summary item detail cannot be undefined.',
    'const undefinedSummaryDetail: undefined = summary.items[0]!.detail;',
    'const sectionInput: SourceControlSectionRegistrationDto = {',
    "  id: 'changes', title: 'Changes', description: null, emptyMessage: null, loadMore: null,",
    "  items: [{ id: 'first', title: 'First', command: null, disabled: false }]",
    '};',
    'declare const section: SourceControlSectionDto;',
    'const sectionDescription: string | null = section.description;',
    'const sectionCommand: string | null = section.items[0]!.command;',
    'const loadMoreCommand: string | null = section.loadMore?.command ?? null;',
    'const textField: SourceControlFormFieldRegistrationDto = { id: \'message\', label: \'Message\' };',
    'const textareaField: SourceControlFormFieldRegistrationDto = {',
    "  id: 'body', label: 'Body', type: 'textarea', value: '', maxLength: 4096",
    '};',
    'const selectField: SourceControlFormFieldRegistrationDto = {',
    "  id: 'branch', label: 'Branch', type: 'select', value: 'main',",
    "  options: [{ value: 'main', label: 'main' }]",
    '};',
    'const checkboxField: SourceControlFormFieldRegistrationDto = {',
    "  id: 'amend', label: 'Amend', type: 'checkbox', value: true",
    '};',
    '// @ts-expect-error Checkbox defaults are boolean, never strings.',
    "const invalidCheckbox: SourceControlFormFieldRegistrationDto = { id: 'amend', label: 'Amend', type: 'checkbox', value: 'yes' };",
    '// @ts-expect-error Select fields require their bounded option DTO list.',
    "const missingSelectOptions: SourceControlFormFieldRegistrationDto = { id: 'branch', label: 'Branch', type: 'select' };",
    '// @ts-expect-error Only select fields carry options.',
    "const textWithOptions: SourceControlFormFieldRegistrationDto = { id: 'message', label: 'Message', options: [{ value: 'x', label: 'X' }] };",
    'const formInput: SourceControlFormRegistrationDto = {',
    '  title: null, submitLabel: null, fields: [textField, textareaField, selectField, checkboxField]',
    '};',
    'declare const form: SourceControlFormDto;',
    'const formTitle: string | null = form.title;',
    'declare const field: SourceControlFormFieldDto;',
    "if (field.type === 'checkbox') {",
    '  const checked: boolean = field.value;',
    '  // @ts-expect-error The checkbox discriminant excludes string values.',
    '  const text: string = field.value;',
    '  void checked; void text;',
    '}',
    "if (field.type === 'select') {",
    '  field.options[0]?.value.toUpperCase();',
    '}',
    'const buttonAction: SourceControlActionRegistrationDto = {',
    "  id: 'commit', title: 'Commit', command: 'acme.commit', form: formInput",
    '};',
    'const toolbarAction: SourceControlActionRegistrationDto = {',
    "  id: 'refresh', title: 'Refresh', command: 'acme.refresh', placement: 'toolbar', icon: 'refresh'",
    '};',
    'const menuAction: SourceControlActionRegistrationDto = {',
    "  id: 'publish', title: 'Publish', command: 'acme.publish', placement: 'menu'",
    '};',
    '// @ts-expect-error Toolbar actions require a semantic icon token.',
    "const toolbarWithoutIcon: SourceControlActionRegistrationDto = { id: 'refresh', title: 'Refresh', command: 'acme.refresh', placement: 'toolbar' };",
    'declare const action: SourceControlActionDto;',
    "if (action.placement === 'toolbar') action.icon.toUpperCase();",
    'const actionForm: SourceControlFormDto | null = action.form;',
    'const stateInput: SourceControlStateRegistrationDto = {',
    "  phase: 'loading', title: null, message: null, summary: summaryInput,",
    '  sections: [sectionInput], actions: [buttonAction, toolbarAction, menuAction]',
    '};',
    'const nullableStateInput: SourceControlStateRegistrationDto = { summary: null };',
    'const state: SourceControlStateDto = {',
    "  phase: 'ready', title: null, message: null, summary: null, sections: [], actions: []",
    '};',
    '// @ts-expect-error A normalized state contains every defaulted field.',
    "const incompleteState: SourceControlStateDto = { phase: 'ready', title: null, message: null, summary: null, sections: [] };",
    '// @ts-expect-error Source-control phases are a closed protocol union.',
    "const invalidPhase: SourceControlStateRegistrationDto = { phase: 'pending' };",
    'const snapshot: SourceControlSnapshot = {',
    "  id: descriptor.id, owner: 'acme', descriptor, state: null, version: 0",
    '};',
    'const maybeState: SourceControlStateDto | null = snapshot.state;',
    'function inspectChange(event: SourceControlChangeEvent): void {',
    "  if (event.type === 'added' || event.type === 'cleared') {",
    '    const empty: null = event.state;',
    '    void empty;',
    '  }',
    "  if (event.type === 'state') event.state.phase.toUpperCase();",
    "  if (event.type === 'removed') {",
    '    // @ts-expect-error Removed snapshots may retain state and therefore require a null check.',
    '    event.state.phase;',
    '    event.state?.phase;',
    '  }',
    '  const id: string = event.id;',
    '  const owner: string = event.owner;',
    '  const version: number = event.version;',
    '  void id; void owner; void version;',
    '}',
    'declare const store: SourceControlStateStoreContract;',
    "const registrationOptions: SourceControlRegistrationOptions = { owner: 'acme', commandPrefix: 'acme.' };",
    'const handle: SourceControlStateHandle = store.register(descriptorInput, registrationOptions);',
    'const updated: SourceControlVersionDto = handle.setState(stateInput);',
    'const cleared: SourceControlVersionDto = handle.clearState();',
    'const subscription: Disposable = store.onDidChange(inspectChange);',
    'const listed: readonly SourceControlSnapshot[] = store.list();',
    "const found: SourceControlSnapshot | null = store.get('acme.scm');",
    "store.disposeOwner('acme');",
    'handle.dispose(); subscription.dispose(); store.dispose();',
    'const storeOptions: SourceControlStateStoreOptions = {',
    '  onError(event: SourceControlStateStoreErrorEvent) {',
    "    const source: 'source-control-listener' = event.source;",
    '    // @ts-expect-error Listener failures remain unknown until narrowed.',
    '    event.error.message;',
    '    void source;',
    '  }',
    '};',
    "const rawValues: SourceControlRawFormValues = { message: 42, amend: true };",
    "const values: SourceControlFormValues = { message: 'ready', amend: true };",
    '// @ts-expect-error Normalized form values contain only strings and booleans.',
    "const invalidValues: SourceControlFormValues = { message: 42 };",
    "const details: SourceControlCommandDetailsDto = { sectionId: 'changes', itemId: 'first', kind: 'item' };",
    '// @ts-expect-error Command detail ids do not use nullable normalization.',
    'const nullableDetails: SourceControlCommandDetailsDto = { sectionId: null };',
    'const payload: SourceControlCommandPayloadDto = {',
    "  sourceControlId: descriptor.id, actionId: 'commit', values, sectionId: 'changes', kind: 'action'",
    '};',
    '// @ts-expect-error A command payload cannot carry arbitrary value objects.',
    "const invalidPayload: SourceControlCommandPayloadDto = { sourceControlId: 'acme.scm', actionId: 'commit', values: { nested: {} } };",
    'type DescriptorIsNotAny = AssertFalse<IsAny<SourceControlDescriptorDto>>;',
    "type DescriptorIdIsNotAny = AssertFalse<IsAny<SourceControlDescriptorDto['id']>>;",
    "type StateIsNotAny = AssertFalse<IsAny<SourceControlSnapshot['state']>>;",
    "type EventStateIsNotAny = AssertFalse<IsAny<SourceControlChangeEvent['state']>>;",
    "type FormValueIsNotAny = AssertFalse<IsAny<SourceControlFormValues[string]>>;",
    "type StoreErrorIsNotAny = AssertFalse<IsAny<SourceControlStateStoreErrorEvent['error']>>;",
    'void descriptorWithNullableCommand; void summaryTitle; void summaryDetail;',
    'void undefinedSummaryDetail; void sectionDescription; void sectionCommand; void loadMoreCommand;',
    'void formTitle; void actionForm; void nullableStateInput; void state; void maybeState;',
    'void updated; void cleared; void listed; void found; void storeOptions; void rawValues;',
    'void details; void payload; void invalidValues; void nullableDetails; void invalidPayload;',
    'void missingIcon; void undefinedOpenCommand; void invalidCheckbox; void missingSelectOptions;',
    'void textWithOptions; void toolbarWithoutIcon; void incompleteState; void invalidPhase;',
    'void (null as unknown as DescriptorIsNotAny);',
    'void (null as unknown as DescriptorIdIsNotAny);',
    'void (null as unknown as StateIsNotAny);',
    'void (null as unknown as EventStateIsNotAny);',
    'void (null as unknown as FormValueIsNotAny);',
    'void (null as unknown as StoreErrorIsNotAny);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__source-control-types-contract.ts',
    source
  });
});
