'use strict';

const path = require('node:path');
const test = require('node:test');
const { assertTypeScriptContract } = require('./support/typescript-contract');

const ROOT = path.resolve(__dirname, '..');

test('utility contracts keep precise return types without creating a renderer service', () => {
  const source = [
    'import {',
    '  detectLanguage,',
    '  isImageFile,',
    '  projectKey,',
    '  isWindowsLocalPath,',
    '  localPathSeparator,',
    '  langDisplayName',
    "} from '../src/utils';",
    'import type {',
    '  DetectedLanguageIdDto,',
    '  LocalPathSeparatorDto,',
    '  ProjectKeyDto,',
    '  RendererPlatform,',
    '  RendererPluginServiceMap,',
    '  RendererServiceMap,',
    '  RendererUtilitiesFacade',
    "} from '../types/renderer-platform';",
    'type Equal<Left, Right> =',
    '  (<Value>() => Value extends Left ? 1 : 2) extends',
    '  (<Value>() => Value extends Right ? 1 : 2) ? true : false;',
    'type AssertTrue<Value extends true> = Value;',
    'type AssertFalse<Value extends false> = Value;',
    'type IsAny<Value> = 0 extends (1 & Value) ? true : false;',
    'type ExpectedLanguageId =',
    "  | 'typescript' | 'javascript' | 'json' | 'python' | 'cpp' | 'c' | 'java'",
    "  | 'markdown' | 'html' | 'css' | 'scss' | 'less' | 'shell' | 'go' | 'rust'",
    "  | 'sql' | 'xml' | 'yaml' | 'plaintext';",
    "type UtilityKey = 'detectLanguage' | 'isImageFile' | 'projectKey' | 'isWindowsLocalPath' | 'localPathSeparator' | 'langDisplayName';",
    'type LanguageIdsAreExact = AssertTrue<Equal<DetectedLanguageIdDto, ExpectedLanguageId>>;',
    "type SeparatorsAreExact = AssertTrue<Equal<LocalPathSeparatorDto, '\\\\' | '/'>>;",
    'type ProjectKeysAreExact = AssertTrue<Equal<ProjectKeyDto, `p${string}`>>;',
    'type FacadeIsExact = AssertTrue<Equal<keyof RendererUtilitiesFacade, UtilityKey>>;',
    "type DetectSignatureIsExact = AssertTrue<Equal<RendererUtilitiesFacade['detectLanguage'], typeof detectLanguage>>;",
    "type ImageSignatureIsExact = AssertTrue<Equal<RendererUtilitiesFacade['isImageFile'], typeof isImageFile>>;",
    "type ProjectSignatureIsExact = AssertTrue<Equal<RendererUtilitiesFacade['projectKey'], typeof projectKey>>;",
    "type WindowsSignatureIsExact = AssertTrue<Equal<RendererUtilitiesFacade['isWindowsLocalPath'], typeof isWindowsLocalPath>>;",
    "type SeparatorSignatureIsExact = AssertTrue<Equal<RendererUtilitiesFacade['localPathSeparator'], typeof localPathSeparator>>;",
    "type DisplaySignatureIsExact = AssertTrue<Equal<RendererUtilitiesFacade['langDisplayName'], typeof langDisplayName>>;",
    'type DetectReturnIsExact = AssertTrue<Equal<ReturnType<typeof detectLanguage>, DetectedLanguageIdDto>>;',
    'type ImageReturnIsExact = AssertTrue<Equal<ReturnType<typeof isImageFile>, boolean>>;',
    'type ProjectReturnIsExact = AssertTrue<Equal<ReturnType<typeof projectKey>, ProjectKeyDto>>;',
    'type WindowsReturnIsExact = AssertTrue<Equal<ReturnType<typeof isWindowsLocalPath>, boolean>>;',
    'type SeparatorReturnIsExact = AssertTrue<Equal<ReturnType<typeof localPathSeparator>, LocalPathSeparatorDto>>;',
    'type DisplayReturnIsExact = AssertTrue<Equal<ReturnType<typeof langDisplayName>, string>>;',
    'type FacadeIsNotAny = AssertFalse<IsAny<RendererUtilitiesFacade>>;',
    'type LanguageIdIsNotAny = AssertFalse<IsAny<DetectedLanguageIdDto>>;',
    'type PathInputIsNotAny = AssertFalse<IsAny<Parameters<typeof isWindowsLocalPath>[0]>>;',
    "type WorkbenchServiceAbsent = AssertFalse<'workbench.utils' extends keyof RendererServiceMap ? true : false>;",
    "type PluginServiceAbsent = AssertFalse<'workbench.utils' extends keyof RendererPluginServiceMap ? true : false>;",
    "const detected: DetectedLanguageIdDto = detectLanguage('main.ts', null);",
    "const image: boolean = isImageFile('image.png');",
    "const key: ProjectKeyDto = projectKey('C:\\\\workspace');",
    "const windowsPath: boolean = isWindowsLocalPath({ toString: () => 'C:\\\\workspace' });",
    "const separator: LocalPathSeparatorDto = localPathSeparator('/workspace');",
    "const displayName: string = langDisplayName('typescript');",
    "const validProjectKey: ProjectKeyDto = 'pabc123';",
    '// @ts-expect-error Project keys retain their p-prefixed template contract.',
    "const invalidProjectKey: ProjectKeyDto = 'qabc123';",
    '// @ts-expect-error Local path separators have exactly two values.',
    "const invalidSeparator: LocalPathSeparatorDto = ':';",
    'declare const facade: RendererUtilitiesFacade;',
    '// @ts-expect-error The typed facade is immutable to consumers.',
    'facade.detectLanguage = detectLanguage;',
    'declare const platform: RendererPlatform;',
    '// @ts-expect-error Utilities are named pure functions, not a workbench service.',
    "platform.services.get('workbench.utils');",
    '// @ts-expect-error Utilities are not part of the downloaded plugin service map.',
    "platform.services.getForPlugin('workbench.utils');",
    'void detected; void image; void key; void windowsPath; void separator; void displayName;',
    'void validProjectKey; void invalidProjectKey; void invalidSeparator; void facade; void platform;',
    'void (false as unknown as LanguageIdsAreExact);',
    'void (false as unknown as SeparatorsAreExact);',
    'void (false as unknown as ProjectKeysAreExact);',
    'void (false as unknown as FacadeIsExact);',
    'void (false as unknown as DetectSignatureIsExact);',
    'void (false as unknown as ImageSignatureIsExact);',
    'void (false as unknown as ProjectSignatureIsExact);',
    'void (false as unknown as WindowsSignatureIsExact);',
    'void (false as unknown as SeparatorSignatureIsExact);',
    'void (false as unknown as DisplaySignatureIsExact);',
    'void (false as unknown as DetectReturnIsExact);',
    'void (false as unknown as ImageReturnIsExact);',
    'void (false as unknown as ProjectReturnIsExact);',
    'void (false as unknown as WindowsReturnIsExact);',
    'void (false as unknown as SeparatorReturnIsExact);',
    'void (false as unknown as DisplayReturnIsExact);',
    'void (false as unknown as FacadeIsNotAny);',
    'void (false as unknown as LanguageIdIsNotAny);',
    'void (false as unknown as PathInputIsNotAny);',
    'void (false as unknown as WorkbenchServiceAbsent);',
    'void (false as unknown as PluginServiceAbsent);'
  ].join('\n');

  assertTypeScriptContract({
    root: ROOT,
    fileName: '__utils-types-contract.ts',
    source
  });
});
